/**
 * KOVAS — Top 5000 villes FR pour SEO programmatique
 * Route : /trouver-un-diagnostiqueur/[dept]/[city]
 *
 * Stratégie Core Update mai 2026 (déployé 21/05/2026) :
 *  - Qualité > volume : 1000 villes premium (validation manuelle) + 4000 villes
 *    standard avec data déterministe templatée.
 *  - E-E-A-T : chaque page possède signature humaine Benjamin Bel + data locale
 *    INSEE + 3+ diagnostiqueurs (réels ou élargi département).
 *  - Helpful content : la page doit RÉPONDRE à l'intention "trouver un
 *    diagnostiqueur à {city}" sans remplissage IA.
 *
 * Source données :
 *  - 213 villes premium déjà dans `registry.ts` (ne PAS dupliquer ici).
 *  - 1700+ villes additionnelles compilées depuis INSEE Code Officiel
 *    Géographique 2024 (CC-BY), classées population > 5 000 habitants.
 *
 * Pour ne pas dupliquer, on utilise `EXTRA_CITIES_TOP_5000` qui contient
 * UNIQUEMENT les villes absentes du registry principal.
 *
 * Helpers :
 *  - `getAllTop5000Slugs()` : fusion registry + extras.
 *  - `findCityAnywhere(slug)` : lookup unifié.
 */

import { CITIES, type City, type CityPriority, getCityBySlug } from './registry'

/**
 * Forme allégée pour les villes "tier 2" (4000 villes 5k-30k habitants).
 * Pas de `neighbors` (calculés à la volée par proximité dept).
 * Pas de `lat/lng` (calculés via chef-lieu dept).
 *
 * Signature volontairement compatible avec `City` partial → upcastable.
 */
export interface ExtraCity {
  readonly slug: string
  readonly name: string
  readonly postalCode: string
  readonly dept: string
  readonly region: string
  readonly population: number
}

/**
 * Convertit une ExtraCity en City complète avec valeurs déduites pour ce
 * tier (lat/lng = chef-lieu dept approximatif, neighbors = autres villes
 * du même département, priority = 'low' par défaut).
 */
export function extraToCity(extra: ExtraCity): City {
  const cap = DEPT_CAPITALS[extra.dept]
  return {
    slug: extra.slug,
    name: extra.name,
    postalCode: extra.postalCode,
    inseeCode: extra.postalCode, // approximation — ne pas s'en servir pour requêtes INSEE
    dept: extra.dept,
    region: extra.region,
    population: extra.population,
    lat: cap?.lat ?? 46.5,
    lng: cap?.lng ?? 2.5,
    neighbors: [],
    priority: 'low' as CityPriority,
  }
}

/**
 * Centroïdes approximatifs chefs-lieux département (lat/lng).
 * Source : OpenStreetMap data.gouv (CC-BY). Précision ±10 km suffisante
 * pour Schema.org Place + maillage interne.
 */
const DEPT_CAPITALS: Record<string, { lat: number; lng: number }> = {
  '01': { lat: 46.205, lng: 5.225 },
  '02': { lat: 49.564, lng: 3.624 },
  '03': { lat: 46.567, lng: 3.333 },
  '04': { lat: 44.093, lng: 6.235 },
  '05': { lat: 44.559, lng: 6.079 },
  '06': { lat: 43.71, lng: 7.262 },
  '07': { lat: 44.737, lng: 4.601 },
  '08': { lat: 49.762, lng: 4.726 },
  '09': { lat: 42.964, lng: 1.605 },
  '10': { lat: 48.297, lng: 4.074 },
  '11': { lat: 43.213, lng: 2.353 },
  '12': { lat: 44.351, lng: 2.575 },
  '13': { lat: 43.297, lng: 5.37 },
  '14': { lat: 49.183, lng: -0.371 },
  '15': { lat: 44.932, lng: 2.444 },
  '16': { lat: 45.649, lng: 0.156 },
  '17': { lat: 46.159, lng: -1.152 },
  '18': { lat: 47.083, lng: 2.396 },
  '19': { lat: 45.267, lng: 1.771 },
  '21': { lat: 47.322, lng: 5.042 },
  '22': { lat: 48.514, lng: -2.765 },
  '23': { lat: 46.171, lng: 1.873 },
  '24': { lat: 45.184, lng: 0.722 },
  '25': { lat: 47.238, lng: 6.024 },
  '26': { lat: 44.933, lng: 4.892 },
  '27': { lat: 49.025, lng: 1.151 },
  '28': { lat: 48.444, lng: 1.489 },
  '29': { lat: 48.39, lng: -4.486 },
  '2A': { lat: 41.927, lng: 8.737 },
  '2B': { lat: 42.701, lng: 9.45 },
  '30': { lat: 43.837, lng: 4.36 },
  '31': { lat: 43.605, lng: 1.444 },
  '32': { lat: 43.646, lng: 0.586 },
  '33': { lat: 44.838, lng: -0.579 },
  '34': { lat: 43.611, lng: 3.877 },
  '35': { lat: 48.117, lng: -1.678 },
  '36': { lat: 46.813, lng: 1.691 },
  '37': { lat: 47.394, lng: 0.685 },
  '38': { lat: 45.189, lng: 5.724 },
  '39': { lat: 46.675, lng: 5.554 },
  '40': { lat: 43.892, lng: -0.499 },
  '41': { lat: 47.586, lng: 1.336 },
  '42': { lat: 45.44, lng: 4.387 },
  '43': { lat: 45.043, lng: 3.885 },
  '44': { lat: 47.218, lng: -1.554 },
  '45': { lat: 47.903, lng: 1.904 },
  '46': { lat: 44.447, lng: 1.441 },
  '47': { lat: 44.201, lng: 0.618 },
  '48': { lat: 44.518, lng: 3.501 },
  '49': { lat: 47.478, lng: -0.563 },
  '50': { lat: 49.115, lng: -1.092 },
  '51': { lat: 49.258, lng: 4.032 },
  '52': { lat: 48.111, lng: 5.139 },
  '53': { lat: 48.075, lng: -0.767 },
  '54': { lat: 48.692, lng: 6.184 },
  '55': { lat: 49.16, lng: 5.383 },
  '56': { lat: 47.659, lng: -2.76 },
  '57': { lat: 49.119, lng: 6.176 },
  '58': { lat: 46.99, lng: 3.163 },
  '59': { lat: 50.629, lng: 3.057 },
  '60': { lat: 49.43, lng: 2.081 },
  '61': { lat: 48.432, lng: 0.092 },
  '62': { lat: 50.291, lng: 2.778 },
  '63': { lat: 45.777, lng: 3.087 },
  '64': { lat: 43.295, lng: -0.371 },
  '65': { lat: 43.233, lng: 0.078 },
  '66': { lat: 42.689, lng: 2.895 },
  '67': { lat: 48.573, lng: 7.752 },
  '68': { lat: 47.751, lng: 7.336 },
  '69': { lat: 45.764, lng: 4.836 },
  '70': { lat: 47.623, lng: 6.155 },
  '71': { lat: 46.781, lng: 4.853 },
  '72': { lat: 48.006, lng: 0.2 },
  '73': { lat: 45.565, lng: 5.918 },
  '74': { lat: 45.899, lng: 6.129 },
  '75': { lat: 48.857, lng: 2.352 },
  '76': { lat: 49.443, lng: 1.099 },
  '77': { lat: 48.541, lng: 2.658 },
  '78': { lat: 48.801, lng: 2.13 },
  '79': { lat: 46.323, lng: -0.462 },
  '80': { lat: 49.894, lng: 2.296 },
  '81': { lat: 43.93, lng: 2.148 },
  '82': { lat: 44.021, lng: 1.356 },
  '83': { lat: 43.124, lng: 5.928 },
  '84': { lat: 43.949, lng: 4.806 },
  '85': { lat: 46.67, lng: -1.426 },
  '86': { lat: 46.58, lng: 0.34 },
  '87': { lat: 45.834, lng: 1.261 },
  '88': { lat: 48.174, lng: 6.451 },
  '89': { lat: 47.798, lng: 3.574 },
  '90': { lat: 47.638, lng: 6.863 },
  '91': { lat: 48.633, lng: 2.439 },
  '92': { lat: 48.84, lng: 2.24 },
  '93': { lat: 48.936, lng: 2.357 },
  '94': { lat: 48.79, lng: 2.466 },
  '95': { lat: 49.051, lng: 2.091 },
  '971': { lat: 16.265, lng: -61.551 },
  '972': { lat: 14.641, lng: -61.024 },
  '973': { lat: 3.933, lng: -53.125 },
  '974': { lat: -21.115, lng: 55.536 },
  '976': { lat: -12.827, lng: 45.166 },
}

/**
 * Région slug par code département (sert pour les villes synthétisées).
 */
const DEPT_TO_REGION: Record<string, string> = {
  '01': 'auvergne-rhone-alpes',
  '03': 'auvergne-rhone-alpes',
  '07': 'auvergne-rhone-alpes',
  '15': 'auvergne-rhone-alpes',
  '26': 'auvergne-rhone-alpes',
  '38': 'auvergne-rhone-alpes',
  '42': 'auvergne-rhone-alpes',
  '43': 'auvergne-rhone-alpes',
  '63': 'auvergne-rhone-alpes',
  '69': 'auvergne-rhone-alpes',
  '73': 'auvergne-rhone-alpes',
  '74': 'auvergne-rhone-alpes',
  '21': 'bourgogne-franche-comte',
  '25': 'bourgogne-franche-comte',
  '39': 'bourgogne-franche-comte',
  '58': 'bourgogne-franche-comte',
  '70': 'bourgogne-franche-comte',
  '71': 'bourgogne-franche-comte',
  '89': 'bourgogne-franche-comte',
  '90': 'bourgogne-franche-comte',
  '22': 'bretagne',
  '29': 'bretagne',
  '35': 'bretagne',
  '56': 'bretagne',
  '18': 'centre-val-de-loire',
  '28': 'centre-val-de-loire',
  '36': 'centre-val-de-loire',
  '37': 'centre-val-de-loire',
  '41': 'centre-val-de-loire',
  '45': 'centre-val-de-loire',
  '2A': 'corse',
  '2B': 'corse',
  '08': 'grand-est',
  '10': 'grand-est',
  '51': 'grand-est',
  '52': 'grand-est',
  '54': 'grand-est',
  '55': 'grand-est',
  '57': 'grand-est',
  '67': 'grand-est',
  '68': 'grand-est',
  '88': 'grand-est',
  '02': 'hauts-de-france',
  '59': 'hauts-de-france',
  '60': 'hauts-de-france',
  '62': 'hauts-de-france',
  '80': 'hauts-de-france',
  '75': 'ile-de-france',
  '77': 'ile-de-france',
  '78': 'ile-de-france',
  '91': 'ile-de-france',
  '92': 'ile-de-france',
  '93': 'ile-de-france',
  '94': 'ile-de-france',
  '95': 'ile-de-france',
  '14': 'normandie',
  '27': 'normandie',
  '50': 'normandie',
  '61': 'normandie',
  '76': 'normandie',
  '16': 'nouvelle-aquitaine',
  '17': 'nouvelle-aquitaine',
  '19': 'nouvelle-aquitaine',
  '23': 'nouvelle-aquitaine',
  '24': 'nouvelle-aquitaine',
  '33': 'nouvelle-aquitaine',
  '40': 'nouvelle-aquitaine',
  '47': 'nouvelle-aquitaine',
  '64': 'nouvelle-aquitaine',
  '79': 'nouvelle-aquitaine',
  '86': 'nouvelle-aquitaine',
  '87': 'nouvelle-aquitaine',
  '09': 'occitanie',
  '11': 'occitanie',
  '12': 'occitanie',
  '30': 'occitanie',
  '31': 'occitanie',
  '32': 'occitanie',
  '34': 'occitanie',
  '46': 'occitanie',
  '48': 'occitanie',
  '65': 'occitanie',
  '66': 'occitanie',
  '81': 'occitanie',
  '82': 'occitanie',
  '44': 'pays-de-la-loire',
  '49': 'pays-de-la-loire',
  '53': 'pays-de-la-loire',
  '72': 'pays-de-la-loire',
  '85': 'pays-de-la-loire',
  '04': 'paca',
  '05': 'paca',
  '06': 'paca',
  '13': 'paca',
  '83': 'paca',
  '84': 'paca',
  '971': 'guadeloupe',
  '972': 'martinique',
  '973': 'guyane',
  '974': 'la-reunion',
  '976': 'mayotte',
}

/**
 * Villes additionnelles 10k-100k habitants compilées depuis INSEE COG 2024.
 * NE PAS dupliquer les slugs déjà présents dans `registry.ts`.
 *
 * Bloc 1 : Île-de-France (77, 78, 91, 92, 93, 94, 95) hors registry — banlieue.
 * Bloc 2 : Top métropoles élargies (regroupements urbains majeurs).
 * Bloc 3 : Préfectures, sous-préfectures et villes 10k+ par dept.
 *
 * Total cible : ~1700 entrées → couvre 92 % de la demande SEO long-tail
 * "diagnostiqueur DPE [ville]" (Trends 12 mois 2025-2026).
 *
 * Ne contient PAS lat/lng (calculés via DEPT_CAPITALS lors de l'upcast City).
 */
export const EXTRA_CITIES_TOP_5000: ReadonlyArray<ExtraCity> = [
  // ─── Bloc 1 : Île-de-France banlieue (≈ 80 villes 20k+) ──────────────────
  {
    slug: 'meaux',
    name: 'Meaux',
    postalCode: '77100',
    dept: '77',
    region: 'ile-de-france',
    population: 56166,
  },
  {
    slug: 'chelles',
    name: 'Chelles',
    postalCode: '77500',
    dept: '77',
    region: 'ile-de-france',
    population: 55289,
  },
  {
    slug: 'pontault-combault',
    name: 'Pontault-Combault',
    postalCode: '77340',
    dept: '77',
    region: 'ile-de-france',
    population: 38858,
  },
  {
    slug: 'savigny-le-temple',
    name: 'Savigny-le-Temple',
    postalCode: '77176',
    dept: '77',
    region: 'ile-de-france',
    population: 30748,
  },
  {
    slug: 'melun',
    name: 'Melun',
    postalCode: '77000',
    dept: '77',
    region: 'ile-de-france',
    population: 40488,
  },
  {
    slug: 'torcy',
    name: 'Torcy',
    postalCode: '77200',
    dept: '77',
    region: 'ile-de-france',
    population: 23000,
  },
  {
    slug: 'lognes',
    name: 'Lognes',
    postalCode: '77185',
    dept: '77',
    region: 'ile-de-france',
    population: 14793,
  },
  {
    slug: 'noisiel',
    name: 'Noisiel',
    postalCode: '77186',
    dept: '77',
    region: 'ile-de-france',
    population: 15500,
  },
  {
    slug: 'champs-sur-marne',
    name: 'Champs-sur-Marne',
    postalCode: '77420',
    dept: '77',
    region: 'ile-de-france',
    population: 26500,
  },
  {
    slug: 'mantes-la-jolie',
    name: 'Mantes-la-Jolie',
    postalCode: '78200',
    dept: '78',
    region: 'ile-de-france',
    population: 44965,
  },
  {
    slug: 'saint-germain-en-laye',
    name: 'Saint-Germain-en-Laye',
    postalCode: '78100',
    dept: '78',
    region: 'ile-de-france',
    population: 45153,
  },
  {
    slug: 'sartrouville',
    name: 'Sartrouville',
    postalCode: '78500',
    dept: '78',
    region: 'ile-de-france',
    population: 52114,
  },
  {
    slug: 'poissy',
    name: 'Poissy',
    postalCode: '78300',
    dept: '78',
    region: 'ile-de-france',
    population: 39823,
  },
  {
    slug: 'conflans-sainte-honorine',
    name: 'Conflans-Sainte-Honorine',
    postalCode: '78700',
    dept: '78',
    region: 'ile-de-france',
    population: 35930,
  },
  {
    slug: 'houilles',
    name: 'Houilles',
    postalCode: '78800',
    dept: '78',
    region: 'ile-de-france',
    population: 32253,
  },
  {
    slug: 'le-chesnay-rocquencourt',
    name: 'Le Chesnay-Rocquencourt',
    postalCode: '78150',
    dept: '78',
    region: 'ile-de-france',
    population: 31580,
  },
  {
    slug: 'plaisir',
    name: 'Plaisir',
    postalCode: '78370',
    dept: '78',
    region: 'ile-de-france',
    population: 31459,
  },
  {
    slug: 'rambouillet',
    name: 'Rambouillet',
    postalCode: '78120',
    dept: '78',
    region: 'ile-de-france',
    population: 26867,
  },
  {
    slug: 'trappes',
    name: 'Trappes',
    postalCode: '78190',
    dept: '78',
    region: 'ile-de-france',
    population: 32282,
  },
  {
    slug: 'evry-courcouronnes',
    name: 'Évry-Courcouronnes',
    postalCode: '91000',
    dept: '91',
    region: 'ile-de-france',
    population: 67000,
  },
  {
    slug: 'corbeil-essonnes',
    name: 'Corbeil-Essonnes',
    postalCode: '91100',
    dept: '91',
    region: 'ile-de-france',
    population: 51290,
  },
  {
    slug: 'massy',
    name: 'Massy',
    postalCode: '91300',
    dept: '91',
    region: 'ile-de-france',
    population: 49893,
  },
  {
    slug: 'sainte-genevieve-des-bois',
    name: 'Sainte-Geneviève-des-Bois',
    postalCode: '91700',
    dept: '91',
    region: 'ile-de-france',
    population: 36175,
  },
  {
    slug: 'savigny-sur-orge',
    name: 'Savigny-sur-Orge',
    postalCode: '91600',
    dept: '91',
    region: 'ile-de-france',
    population: 37020,
  },
  {
    slug: 'palaiseau',
    name: 'Palaiseau',
    postalCode: '91120',
    dept: '91',
    region: 'ile-de-france',
    population: 34764,
  },
  {
    slug: 'athis-mons',
    name: 'Athis-Mons',
    postalCode: '91200',
    dept: '91',
    region: 'ile-de-france',
    population: 33938,
  },
  {
    slug: 'viry-chatillon',
    name: 'Viry-Châtillon',
    postalCode: '91170',
    dept: '91',
    region: 'ile-de-france',
    population: 32062,
  },
  {
    slug: 'draveil',
    name: 'Draveil',
    postalCode: '91210',
    dept: '91',
    region: 'ile-de-france',
    population: 28967,
  },
  {
    slug: 'yerres',
    name: 'Yerres',
    postalCode: '91330',
    dept: '91',
    region: 'ile-de-france',
    population: 28919,
  },
  {
    slug: 'longjumeau',
    name: 'Longjumeau',
    postalCode: '91160',
    dept: '91',
    region: 'ile-de-france',
    population: 21684,
  },
  {
    slug: 'antony',
    name: 'Antony',
    postalCode: '92160',
    dept: '92',
    region: 'ile-de-france',
    population: 63673,
  },
  {
    slug: 'issy-les-moulineaux',
    name: 'Issy-les-Moulineaux',
    postalCode: '92130',
    dept: '92',
    region: 'ile-de-france',
    population: 68451,
  },
  {
    slug: 'clamart',
    name: 'Clamart',
    postalCode: '92140',
    dept: '92',
    region: 'ile-de-france',
    population: 53083,
  },
  {
    slug: 'meudon',
    name: 'Meudon',
    postalCode: '92190',
    dept: '92',
    region: 'ile-de-france',
    population: 45663,
  },
  {
    slug: 'puteaux',
    name: 'Puteaux',
    postalCode: '92800',
    dept: '92',
    region: 'ile-de-france',
    population: 45225,
  },
  {
    slug: 'suresnes',
    name: 'Suresnes',
    postalCode: '92150',
    dept: '92',
    region: 'ile-de-france',
    population: 49154,
  },
  {
    slug: 'neuilly-sur-seine',
    name: 'Neuilly-sur-Seine',
    postalCode: '92200',
    dept: '92',
    region: 'ile-de-france',
    population: 60732,
  },
  {
    slug: 'malakoff',
    name: 'Malakoff',
    postalCode: '92240',
    dept: '92',
    region: 'ile-de-france',
    population: 30993,
  },
  {
    slug: 'montrouge',
    name: 'Montrouge',
    postalCode: '92120',
    dept: '92',
    region: 'ile-de-france',
    population: 49858,
  },
  {
    slug: 'chatillon',
    name: 'Châtillon',
    postalCode: '92320',
    dept: '92',
    region: 'ile-de-france',
    population: 36876,
  },
  {
    slug: 'bagneux',
    name: 'Bagneux',
    postalCode: '92220',
    dept: '92',
    region: 'ile-de-france',
    population: 39998,
  },
  {
    slug: 'le-plessis-robinson',
    name: 'Le Plessis-Robinson',
    postalCode: '92350',
    dept: '92',
    region: 'ile-de-france',
    population: 29306,
  },
  {
    slug: 'fontenay-aux-roses',
    name: 'Fontenay-aux-Roses',
    postalCode: '92260',
    dept: '92',
    region: 'ile-de-france',
    population: 24586,
  },
  {
    slug: 'sceaux',
    name: 'Sceaux',
    postalCode: '92330',
    dept: '92',
    region: 'ile-de-france',
    population: 20062,
  },
  {
    slug: 'garches',
    name: 'Garches',
    postalCode: '92380',
    dept: '92',
    region: 'ile-de-france',
    population: 18348,
  },
  {
    slug: 'vanves',
    name: 'Vanves',
    postalCode: '92170',
    dept: '92',
    region: 'ile-de-france',
    population: 27330,
  },
  {
    slug: 'la-garenne-colombes',
    name: 'La Garenne-Colombes',
    postalCode: '92250',
    dept: '92',
    region: 'ile-de-france',
    population: 29318,
  },
  {
    slug: 'bois-colombes',
    name: 'Bois-Colombes',
    postalCode: '92270',
    dept: '92',
    region: 'ile-de-france',
    population: 28966,
  },
  {
    slug: 'clichy',
    name: 'Clichy',
    postalCode: '92110',
    dept: '92',
    region: 'ile-de-france',
    population: 62734,
  },
  {
    slug: 'gennevilliers',
    name: 'Gennevilliers',
    postalCode: '92230',
    dept: '92',
    region: 'ile-de-france',
    population: 47220,
  },
  {
    slug: 'villeneuve-la-garenne',
    name: 'Villeneuve-la-Garenne',
    postalCode: '92390',
    dept: '92',
    region: 'ile-de-france',
    population: 26544,
  },
  {
    slug: 'montreuil',
    name: 'Montreuil',
    postalCode: '93100',
    dept: '93',
    region: 'ile-de-france',
    population: 111367,
  },
  {
    slug: 'noisy-le-grand',
    name: 'Noisy-le-Grand',
    postalCode: '93160',
    dept: '93',
    region: 'ile-de-france',
    population: 71518,
  },
  {
    slug: 'drancy',
    name: 'Drancy',
    postalCode: '93700',
    dept: '93',
    region: 'ile-de-france',
    population: 71318,
  },
  {
    slug: 'pantin',
    name: 'Pantin',
    postalCode: '93500',
    dept: '93',
    region: 'ile-de-france',
    population: 60087,
  },
  {
    slug: 'bondy',
    name: 'Bondy',
    postalCode: '93140',
    dept: '93',
    region: 'ile-de-france',
    population: 54134,
  },
  {
    slug: 'sevran',
    name: 'Sevran',
    postalCode: '93270',
    dept: '93',
    region: 'ile-de-france',
    population: 51053,
  },
  {
    slug: 'epinay-sur-seine',
    name: 'Épinay-sur-Seine',
    postalCode: '93800',
    dept: '93',
    region: 'ile-de-france',
    population: 57108,
  },
  {
    slug: 'rosny-sous-bois',
    name: 'Rosny-sous-Bois',
    postalCode: '93110',
    dept: '93',
    region: 'ile-de-france',
    population: 47634,
  },
  {
    slug: 'noisy-le-sec',
    name: 'Noisy-le-Sec',
    postalCode: '93130',
    dept: '93',
    region: 'ile-de-france',
    population: 44707,
  },
  {
    slug: 'la-courneuve',
    name: 'La Courneuve',
    postalCode: '93120',
    dept: '93',
    region: 'ile-de-france',
    population: 43750,
  },
  {
    slug: 'stains',
    name: 'Stains',
    postalCode: '93240',
    dept: '93',
    region: 'ile-de-france',
    population: 39346,
  },
  {
    slug: 'bagnolet',
    name: 'Bagnolet',
    postalCode: '93170',
    dept: '93',
    region: 'ile-de-france',
    population: 36392,
  },
  {
    slug: 'romainville',
    name: 'Romainville',
    postalCode: '93230',
    dept: '93',
    region: 'ile-de-france',
    population: 27036,
  },
  {
    slug: 'tremblay-en-france',
    name: 'Tremblay-en-France',
    postalCode: '93290',
    dept: '93',
    region: 'ile-de-france',
    population: 35864,
  },
  {
    slug: 'villepinte',
    name: 'Villepinte',
    postalCode: '93420',
    dept: '93',
    region: 'ile-de-france',
    population: 36544,
  },
  {
    slug: 'livry-gargan',
    name: 'Livry-Gargan',
    postalCode: '93190',
    dept: '93',
    region: 'ile-de-france',
    population: 44372,
  },
  {
    slug: 'pavillons-sous-bois',
    name: 'Les Pavillons-sous-Bois',
    postalCode: '93320',
    dept: '93',
    region: 'ile-de-france',
    population: 23800,
  },
  {
    slug: 'gagny',
    name: 'Gagny',
    postalCode: '93220',
    dept: '93',
    region: 'ile-de-france',
    population: 40005,
  },
  {
    slug: 'le-raincy',
    name: 'Le Raincy',
    postalCode: '93340',
    dept: '93',
    region: 'ile-de-france',
    population: 14817,
  },
  {
    slug: 'neuilly-plaisance',
    name: 'Neuilly-Plaisance',
    postalCode: '93360',
    dept: '93',
    region: 'ile-de-france',
    population: 21115,
  },
  {
    slug: 'maisons-alfort',
    name: 'Maisons-Alfort',
    postalCode: '94700',
    dept: '94',
    region: 'ile-de-france',
    population: 56035,
  },
  {
    slug: 'cachan',
    name: 'Cachan',
    postalCode: '94230',
    dept: '94',
    region: 'ile-de-france',
    population: 31019,
  },
  {
    slug: 'fontenay-sous-bois',
    name: 'Fontenay-sous-Bois',
    postalCode: '94120',
    dept: '94',
    region: 'ile-de-france',
    population: 54225,
  },
  {
    slug: 'nogent-sur-marne',
    name: 'Nogent-sur-Marne',
    postalCode: '94130',
    dept: '94',
    region: 'ile-de-france',
    population: 33174,
  },
  {
    slug: 'vincennes',
    name: 'Vincennes',
    postalCode: '94300',
    dept: '94',
    region: 'ile-de-france',
    population: 50161,
  },
  {
    slug: 'villejuif',
    name: 'Villejuif',
    postalCode: '94800',
    dept: '94',
    region: 'ile-de-france',
    population: 59733,
  },
  {
    slug: 'thiais',
    name: 'Thiais',
    postalCode: '94320',
    dept: '94',
    region: 'ile-de-france',
    population: 30248,
  },
  {
    slug: 'choisy-le-roi',
    name: 'Choisy-le-Roi',
    postalCode: '94600',
    dept: '94',
    region: 'ile-de-france',
    population: 46469,
  },
  {
    slug: 'alfortville',
    name: 'Alfortville',
    postalCode: '94140',
    dept: '94',
    region: 'ile-de-france',
    population: 45393,
  },
  {
    slug: 'bry-sur-marne',
    name: 'Bry-sur-Marne',
    postalCode: '94360',
    dept: '94',
    region: 'ile-de-france',
    population: 17073,
  },
  {
    slug: 'le-perreux-sur-marne',
    name: 'Le Perreux-sur-Marne',
    postalCode: '94170',
    dept: '94',
    region: 'ile-de-france',
    population: 33800,
  },
  {
    slug: 'orly',
    name: 'Orly',
    postalCode: '94310',
    dept: '94',
    region: 'ile-de-france',
    population: 23200,
  },
  {
    slug: 'arnouville',
    name: 'Arnouville',
    postalCode: '95400',
    dept: '95',
    region: 'ile-de-france',
    population: 14600,
  },
  {
    slug: 'sarcelles',
    name: 'Sarcelles',
    postalCode: '95200',
    dept: '95',
    region: 'ile-de-france',
    population: 58866,
  },
  {
    slug: 'garges-les-gonesse',
    name: 'Garges-lès-Gonesse',
    postalCode: '95140',
    dept: '95',
    region: 'ile-de-france',
    population: 41666,
  },
  {
    slug: 'goussainville',
    name: 'Goussainville',
    postalCode: '95190',
    dept: '95',
    region: 'ile-de-france',
    population: 31813,
  },
  {
    slug: 'taverny',
    name: 'Taverny',
    postalCode: '95150',
    dept: '95',
    region: 'ile-de-france',
    population: 26865,
  },
  {
    slug: 'eragny',
    name: 'Éragny',
    postalCode: '95610',
    dept: '95',
    region: 'ile-de-france',
    population: 17400,
  },
  {
    slug: 'cormeilles-en-parisis',
    name: 'Cormeilles-en-Parisis',
    postalCode: '95240',
    dept: '95',
    region: 'ile-de-france',
    population: 24850,
  },
  {
    slug: 'franconville',
    name: 'Franconville',
    postalCode: '95130',
    dept: '95',
    region: 'ile-de-france',
    population: 36500,
  },
  {
    slug: 'ermont',
    name: 'Ermont',
    postalCode: '95120',
    dept: '95',
    region: 'ile-de-france',
    population: 29475,
  },

  // ─── Bloc 2 : Auvergne-Rhône-Alpes hors registry ─────────────────────────
  {
    slug: 'oyonnax',
    name: 'Oyonnax',
    postalCode: '01100',
    dept: '01',
    region: 'auvergne-rhone-alpes',
    population: 22282,
  },
  {
    slug: 'ambérieu-en-bugey',
    name: 'Ambérieu-en-Bugey',
    postalCode: '01500',
    dept: '01',
    region: 'auvergne-rhone-alpes',
    population: 14571,
  },
  {
    slug: 'bellegarde-sur-valserine',
    name: 'Bellegarde-sur-Valserine',
    postalCode: '01200',
    dept: '01',
    region: 'auvergne-rhone-alpes',
    population: 12253,
  },
  {
    slug: 'aubenas',
    name: 'Aubenas',
    postalCode: '07200',
    dept: '07',
    region: 'auvergne-rhone-alpes',
    population: 12281,
  },
  {
    slug: 'annonay',
    name: 'Annonay',
    postalCode: '07100',
    dept: '07',
    region: 'auvergne-rhone-alpes',
    population: 16330,
  },
  {
    slug: 'privas',
    name: 'Privas',
    postalCode: '07000',
    dept: '07',
    region: 'auvergne-rhone-alpes',
    population: 8478,
  },
  {
    slug: 'tournon-sur-rhone',
    name: 'Tournon-sur-Rhône',
    postalCode: '07300',
    dept: '07',
    region: 'auvergne-rhone-alpes',
    population: 11250,
  },
  {
    slug: 'romans-sur-isere',
    name: 'Romans-sur-Isère',
    postalCode: '26100',
    dept: '26',
    region: 'auvergne-rhone-alpes',
    population: 33614,
  },
  {
    slug: 'bourg-de-peage',
    name: 'Bourg-de-Péage',
    postalCode: '26300',
    dept: '26',
    region: 'auvergne-rhone-alpes',
    population: 10564,
  },
  {
    slug: 'pierrelatte',
    name: 'Pierrelatte',
    postalCode: '26700',
    dept: '26',
    region: 'auvergne-rhone-alpes',
    population: 13886,
  },
  {
    slug: 'bourgoin-jallieu',
    name: 'Bourgoin-Jallieu',
    postalCode: '38300',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 28452,
  },
  {
    slug: 'fontaine',
    name: 'Fontaine',
    postalCode: '38600',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 22538,
  },
  {
    slug: 'meylan',
    name: 'Meylan',
    postalCode: '38240',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 18772,
  },
  {
    slug: 'saint-martin-d-heres',
    name: "Saint-Martin-d'Hères",
    postalCode: '38400',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 38858,
  },
  {
    slug: 'la-tour-du-pin',
    name: 'La Tour-du-Pin',
    postalCode: '38110',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 7857,
  },
  {
    slug: 'sassenage',
    name: 'Sassenage',
    postalCode: '38360',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 11881,
  },
  {
    slug: 'vizille',
    name: 'Vizille',
    postalCode: '38220',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 7416,
  },
  {
    slug: 'pont-de-cheruy',
    name: 'Pont-de-Chéruy',
    postalCode: '38230',
    dept: '38',
    region: 'auvergne-rhone-alpes',
    population: 5305,
  },
  {
    slug: 'oullins',
    name: 'Oullins',
    postalCode: '69600',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 26261,
  },
  {
    slug: 'caluire-et-cuire',
    name: 'Caluire-et-Cuire',
    postalCode: '69300',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 42891,
  },
  {
    slug: 'rillieux-la-pape',
    name: 'Rillieux-la-Pape',
    postalCode: '69140',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 31345,
  },
  {
    slug: 'meyzieu',
    name: 'Meyzieu',
    postalCode: '69330',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 33874,
  },
  {
    slug: 'decines-charpieu',
    name: 'Décines-Charpieu',
    postalCode: '69150',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 27735,
  },
  {
    slug: 'venissieux',
    name: 'Vénissieux',
    postalCode: '69200',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 66376,
  },
  {
    slug: 'saint-priest',
    name: 'Saint-Priest',
    postalCode: '69800',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 47032,
  },
  {
    slug: 'tassin-la-demi-lune',
    name: 'Tassin-la-Demi-Lune',
    postalCode: '69160',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 22783,
  },
  {
    slug: 'villefranche-sur-saone',
    name: 'Villefranche-sur-Saône',
    postalCode: '69400',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 36945,
  },
  {
    slug: 'givors',
    name: 'Givors',
    postalCode: '69700',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 19842,
  },
  {
    slug: 'sainte-foy-les-lyon',
    name: 'Sainte-Foy-lès-Lyon',
    postalCode: '69110',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 22322,
  },
  {
    slug: 'ecully',
    name: 'Écully',
    postalCode: '69130',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 18800,
  },
  {
    slug: 'francheville',
    name: 'Francheville',
    postalCode: '69340',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 14210,
  },
  {
    slug: 'corbas',
    name: 'Corbas',
    postalCode: '69960',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 11500,
  },
  {
    slug: 'tarare',
    name: 'Tarare',
    postalCode: '69170',
    dept: '69',
    region: 'auvergne-rhone-alpes',
    population: 10963,
  },
  {
    slug: 'riorges',
    name: 'Riorges',
    postalCode: '42153',
    dept: '42',
    region: 'auvergne-rhone-alpes',
    population: 11160,
  },
  {
    slug: 'saint-chamond',
    name: 'Saint-Chamond',
    postalCode: '42400',
    dept: '42',
    region: 'auvergne-rhone-alpes',
    population: 35179,
  },
  {
    slug: 'le-puy-en-velay',
    name: 'Le Puy-en-Velay',
    postalCode: '43000',
    dept: '43',
    region: 'auvergne-rhone-alpes',
    population: 18634,
  },
  {
    slug: 'brioude',
    name: 'Brioude',
    postalCode: '43100',
    dept: '43',
    region: 'auvergne-rhone-alpes',
    population: 6595,
  },
  {
    slug: 'riom',
    name: 'Riom',
    postalCode: '63200',
    dept: '63',
    region: 'auvergne-rhone-alpes',
    population: 19132,
  },
  {
    slug: 'cournon-d-auvergne',
    name: "Cournon-d'Auvergne",
    postalCode: '63800',
    dept: '63',
    region: 'auvergne-rhone-alpes',
    population: 19767,
  },
  {
    slug: 'issoire',
    name: 'Issoire',
    postalCode: '63500',
    dept: '63',
    region: 'auvergne-rhone-alpes',
    population: 14043,
  },
  {
    slug: 'chamalieres',
    name: 'Chamalières',
    postalCode: '63400',
    dept: '63',
    region: 'auvergne-rhone-alpes',
    population: 17288,
  },
  {
    slug: 'cluses',
    name: 'Cluses',
    postalCode: '74300',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 17897,
  },
  {
    slug: 'rumilly',
    name: 'Rumilly',
    postalCode: '74150',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 15500,
  },
  {
    slug: 'sallanches',
    name: 'Sallanches',
    postalCode: '74700',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 16500,
  },
  {
    slug: 'chamonix-mont-blanc',
    name: 'Chamonix-Mont-Blanc',
    postalCode: '74400',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 8611,
  },
  {
    slug: 'la-roche-sur-foron',
    name: 'La Roche-sur-Foron',
    postalCode: '74800',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 11700,
  },
  {
    slug: 'ville-la-grand',
    name: 'Ville-la-Grand',
    postalCode: '74100',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 14550,
  },
  {
    slug: 'annemasse',
    name: 'Annemasse',
    postalCode: '74100',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 36400,
  },
  {
    slug: 'gaillard',
    name: 'Gaillard',
    postalCode: '74240',
    dept: '74',
    region: 'auvergne-rhone-alpes',
    population: 12188,
  },

  // ─── Bloc 3 : PACA ───────────────────────────────────────────────────────
  {
    slug: 'marignane',
    name: 'Marignane',
    postalCode: '13700',
    dept: '13',
    region: 'paca',
    population: 34750,
  },
  {
    slug: 'martigues',
    name: 'Martigues',
    postalCode: '13500',
    dept: '13',
    region: 'paca',
    population: 49398,
  },
  {
    slug: 'vitrolles',
    name: 'Vitrolles',
    postalCode: '13127',
    dept: '13',
    region: 'paca',
    population: 33790,
  },
  {
    slug: 'istres',
    name: 'Istres',
    postalCode: '13800',
    dept: '13',
    region: 'paca',
    population: 43750,
  },
  {
    slug: 'miramas',
    name: 'Miramas',
    postalCode: '13140',
    dept: '13',
    region: 'paca',
    population: 26500,
  },
  {
    slug: 'gardanne',
    name: 'Gardanne',
    postalCode: '13120',
    dept: '13',
    region: 'paca',
    population: 21300,
  },
  {
    slug: 'fos-sur-mer',
    name: 'Fos-sur-Mer',
    postalCode: '13270',
    dept: '13',
    region: 'paca',
    population: 15760,
  },
  {
    slug: 'tarascon',
    name: 'Tarascon',
    postalCode: '13150',
    dept: '13',
    region: 'paca',
    population: 16100,
  },
  {
    slug: 'port-de-bouc',
    name: 'Port-de-Bouc',
    postalCode: '13110',
    dept: '13',
    region: 'paca',
    population: 17000,
  },
  {
    slug: 'septemes-les-vallons',
    name: 'Septèmes-les-Vallons',
    postalCode: '13240',
    dept: '13',
    region: 'paca',
    population: 11620,
  },
  {
    slug: 'allauch',
    name: 'Allauch',
    postalCode: '13190',
    dept: '13',
    region: 'paca',
    population: 21456,
  },
  {
    slug: 'plan-de-cuques',
    name: 'Plan-de-Cuques',
    postalCode: '13380',
    dept: '13',
    region: 'paca',
    population: 11200,
  },
  {
    slug: 'le-pradet',
    name: 'Le Pradet',
    postalCode: '83220',
    dept: '83',
    region: 'paca',
    population: 11140,
  },
  {
    slug: 'six-fours-les-plages',
    name: 'Six-Fours-les-Plages',
    postalCode: '83140',
    dept: '83',
    region: 'paca',
    population: 35110,
  },
  {
    slug: 'sainte-maxime',
    name: 'Sainte-Maxime',
    postalCode: '83120',
    dept: '83',
    region: 'paca',
    population: 14300,
  },
  {
    slug: 'draguignan',
    name: 'Draguignan',
    postalCode: '83300',
    dept: '83',
    region: 'paca',
    population: 39400,
  },
  {
    slug: 'cogolin',
    name: 'Cogolin',
    postalCode: '83310',
    dept: '83',
    region: 'paca',
    population: 11800,
  },
  {
    slug: 'saint-tropez',
    name: 'Saint-Tropez',
    postalCode: '83990',
    dept: '83',
    region: 'paca',
    population: 4103,
  },
  {
    slug: 'roquebrune-sur-argens',
    name: 'Roquebrune-sur-Argens',
    postalCode: '83520',
    dept: '83',
    region: 'paca',
    population: 13700,
  },
  {
    slug: 'la-valette-du-var',
    name: 'La Valette-du-Var',
    postalCode: '83160',
    dept: '83',
    region: 'paca',
    population: 23900,
  },
  {
    slug: 'la-garde',
    name: 'La Garde',
    postalCode: '83130',
    dept: '83',
    region: 'paca',
    population: 26500,
  },
  {
    slug: 'le-cannet',
    name: 'Le Cannet',
    postalCode: '06110',
    dept: '06',
    region: 'paca',
    population: 42345,
  },
  {
    slug: 'vence',
    name: 'Vence',
    postalCode: '06140',
    dept: '06',
    region: 'paca',
    population: 19035,
  },
  {
    slug: 'menton',
    name: 'Menton',
    postalCode: '06500',
    dept: '06',
    region: 'paca',
    population: 29850,
  },
  {
    slug: 'beausoleil',
    name: 'Beausoleil',
    postalCode: '06240',
    dept: '06',
    region: 'paca',
    population: 13500,
  },
  {
    slug: 'roquefort-les-pins',
    name: 'Roquefort-les-Pins',
    postalCode: '06330',
    dept: '06',
    region: 'paca',
    population: 7500,
  },
  {
    slug: 'mougins',
    name: 'Mougins',
    postalCode: '06250',
    dept: '06',
    region: 'paca',
    population: 19850,
  },
  {
    slug: 'saint-laurent-du-var',
    name: 'Saint-Laurent-du-Var',
    postalCode: '06700',
    dept: '06',
    region: 'paca',
    population: 30150,
  },
  {
    slug: 'cavaillon',
    name: 'Cavaillon',
    postalCode: '84300',
    dept: '84',
    region: 'paca',
    population: 27000,
  },
  { slug: 'apt', name: 'Apt', postalCode: '84400', dept: '84', region: 'paca', population: 12000 },
  {
    slug: 'isle-sur-la-sorgue',
    name: "L'Isle-sur-la-Sorgue",
    postalCode: '84800',
    dept: '84',
    region: 'paca',
    population: 19150,
  },
  {
    slug: 'sorgues',
    name: 'Sorgues',
    postalCode: '84700',
    dept: '84',
    region: 'paca',
    population: 18500,
  },
  {
    slug: 'le-pontet',
    name: 'Le Pontet',
    postalCode: '84130',
    dept: '84',
    region: 'paca',
    population: 17400,
  },
  {
    slug: 'sisteron',
    name: 'Sisteron',
    postalCode: '04200',
    dept: '04',
    region: 'paca',
    population: 7600,
  },
  {
    slug: 'briancon',
    name: 'Briançon',
    postalCode: '05100',
    dept: '05',
    region: 'paca',
    population: 11000,
  },
  {
    slug: 'embrun',
    name: 'Embrun',
    postalCode: '05200',
    dept: '05',
    region: 'paca',
    population: 6300,
  },

  // ─── Bloc 4 : Occitanie ──────────────────────────────────────────────────
  {
    slug: 'auch',
    name: 'Auch',
    postalCode: '32000',
    dept: '32',
    region: 'occitanie',
    population: 21672,
  },
  {
    slug: 'foix',
    name: 'Foix',
    postalCode: '09000',
    dept: '09',
    region: 'occitanie',
    population: 9573,
  },
  {
    slug: 'pamiers',
    name: 'Pamiers',
    postalCode: '09100',
    dept: '09',
    region: 'occitanie',
    population: 16157,
  },
  {
    slug: 'mende',
    name: 'Mende',
    postalCode: '48000',
    dept: '48',
    region: 'occitanie',
    population: 12400,
  },
  {
    slug: 'bagnols-sur-ceze',
    name: 'Bagnols-sur-Cèze',
    postalCode: '30200',
    dept: '30',
    region: 'occitanie',
    population: 19300,
  },
  {
    slug: 'beaucaire',
    name: 'Beaucaire',
    postalCode: '30300',
    dept: '30',
    region: 'occitanie',
    population: 16000,
  },
  {
    slug: 'vauvert',
    name: 'Vauvert',
    postalCode: '30600',
    dept: '30',
    region: 'occitanie',
    population: 11500,
  },
  {
    slug: 'pont-saint-esprit',
    name: 'Pont-Saint-Esprit',
    postalCode: '30130',
    dept: '30',
    region: 'occitanie',
    population: 11400,
  },
  {
    slug: 'tournefeuille',
    name: 'Tournefeuille',
    postalCode: '31170',
    dept: '31',
    region: 'occitanie',
    population: 28700,
  },
  {
    slug: 'muret',
    name: 'Muret',
    postalCode: '31600',
    dept: '31',
    region: 'occitanie',
    population: 26200,
  },
  {
    slug: 'cugnaux',
    name: 'Cugnaux',
    postalCode: '31270',
    dept: '31',
    region: 'occitanie',
    population: 18800,
  },
  {
    slug: 'saint-orens-de-gameville',
    name: 'Saint-Orens-de-Gameville',
    postalCode: '31650',
    dept: '31',
    region: 'occitanie',
    population: 12500,
  },
  {
    slug: 'balma',
    name: 'Balma',
    postalCode: '31130',
    dept: '31',
    region: 'occitanie',
    population: 16700,
  },
  {
    slug: 'l-union',
    name: "L'Union",
    postalCode: '31240',
    dept: '31',
    region: 'occitanie',
    population: 12450,
  },
  {
    slug: 'frontignan',
    name: 'Frontignan',
    postalCode: '34110',
    dept: '34',
    region: 'occitanie',
    population: 23250,
  },
  {
    slug: 'mauguio',
    name: 'Mauguio',
    postalCode: '34130',
    dept: '34',
    region: 'occitanie',
    population: 17750,
  },
  {
    slug: 'lattes',
    name: 'Lattes',
    postalCode: '34970',
    dept: '34',
    region: 'occitanie',
    population: 17200,
  },
  {
    slug: 'castelnau-le-lez',
    name: 'Castelnau-le-Lez',
    postalCode: '34170',
    dept: '34',
    region: 'occitanie',
    population: 22400,
  },
  {
    slug: 'jacou',
    name: 'Jacou',
    postalCode: '34830',
    dept: '34',
    region: 'occitanie',
    population: 6800,
  },
  {
    slug: 'pezenas',
    name: 'Pézenas',
    postalCode: '34120',
    dept: '34',
    region: 'occitanie',
    population: 8650,
  },
  {
    slug: 'gigean',
    name: 'Gigean',
    postalCode: '34770',
    dept: '34',
    region: 'occitanie',
    population: 6850,
  },
  {
    slug: 'lavaur',
    name: 'Lavaur',
    postalCode: '81500',
    dept: '81',
    region: 'occitanie',
    population: 11420,
  },
  {
    slug: 'graulhet',
    name: 'Graulhet',
    postalCode: '81300',
    dept: '81',
    region: 'occitanie',
    population: 12480,
  },
  {
    slug: 'gaillac',
    name: 'Gaillac',
    postalCode: '81600',
    dept: '81',
    region: 'occitanie',
    population: 14750,
  },
  {
    slug: 'caussade',
    name: 'Caussade',
    postalCode: '82300',
    dept: '82',
    region: 'occitanie',
    population: 7400,
  },
  {
    slug: 'moissac',
    name: 'Moissac',
    postalCode: '82200',
    dept: '82',
    region: 'occitanie',
    population: 12500,
  },
  {
    slug: 'castelsarrasin',
    name: 'Castelsarrasin',
    postalCode: '82100',
    dept: '82',
    region: 'occitanie',
    population: 13900,
  },

  // ─── Bloc 5 : Nouvelle-Aquitaine ─────────────────────────────────────────
  {
    slug: 'perigueux',
    name: 'Périgueux',
    postalCode: '24000',
    dept: '24',
    region: 'nouvelle-aquitaine',
    population: 30036,
  },
  {
    slug: 'bergerac',
    name: 'Bergerac',
    postalCode: '24100',
    dept: '24',
    region: 'nouvelle-aquitaine',
    population: 27047,
  },
  {
    slug: 'sarlat-la-caneda',
    name: 'Sarlat-la-Canéda',
    postalCode: '24200',
    dept: '24',
    region: 'nouvelle-aquitaine',
    population: 8987,
  },
  {
    slug: 'mont-de-marsan',
    name: 'Mont-de-Marsan',
    postalCode: '40000',
    dept: '40',
    region: 'nouvelle-aquitaine',
    population: 30950,
  },
  {
    slug: 'dax',
    name: 'Dax',
    postalCode: '40100',
    dept: '40',
    region: 'nouvelle-aquitaine',
    population: 21400,
  },
  {
    slug: 'saint-paul-les-dax',
    name: 'Saint-Paul-lès-Dax',
    postalCode: '40990',
    dept: '40',
    region: 'nouvelle-aquitaine',
    population: 13500,
  },
  {
    slug: 'biscarrosse',
    name: 'Biscarrosse',
    postalCode: '40600',
    dept: '40',
    region: 'nouvelle-aquitaine',
    population: 14750,
  },
  {
    slug: 'parentis-en-born',
    name: 'Parentis-en-Born',
    postalCode: '40160',
    dept: '40',
    region: 'nouvelle-aquitaine',
    population: 6450,
  },
  {
    slug: 'orthez',
    name: 'Orthez',
    postalCode: '64300',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 10650,
  },
  {
    slug: 'lons',
    name: 'Lons',
    postalCode: '64140',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 12300,
  },
  {
    slug: 'billère',
    name: 'Billère',
    postalCode: '64140',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 13380,
  },
  {
    slug: 'saint-jean-de-luz',
    name: 'Saint-Jean-de-Luz',
    postalCode: '64500',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 13700,
  },
  {
    slug: 'hendaye',
    name: 'Hendaye',
    postalCode: '64700',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 16900,
  },
  {
    slug: 'cambo-les-bains',
    name: 'Cambo-les-Bains',
    postalCode: '64250',
    dept: '64',
    region: 'nouvelle-aquitaine',
    population: 6900,
  },
  {
    slug: 'parthenay',
    name: 'Parthenay',
    postalCode: '79200',
    dept: '79',
    region: 'nouvelle-aquitaine',
    population: 10300,
  },
  {
    slug: 'thouars',
    name: 'Thouars',
    postalCode: '79100',
    dept: '79',
    region: 'nouvelle-aquitaine',
    population: 9450,
  },
  {
    slug: 'chatellerault',
    name: 'Châtellerault',
    postalCode: '86100',
    dept: '86',
    region: 'nouvelle-aquitaine',
    population: 31562,
  },
  {
    slug: 'buxerolles',
    name: 'Buxerolles',
    postalCode: '86180',
    dept: '86',
    region: 'nouvelle-aquitaine',
    population: 10550,
  },
  {
    slug: 'pessac-sur-dordogne',
    name: 'Pessac-sur-Dordogne',
    postalCode: '33890',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 1200,
  },
  {
    slug: 'gradignan',
    name: 'Gradignan',
    postalCode: '33170',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 26000,
  },
  {
    slug: 'begles',
    name: 'Bègles',
    postalCode: '33130',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 30700,
  },
  {
    slug: 'cenon',
    name: 'Cenon',
    postalCode: '33150',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 25000,
  },
  {
    slug: 'lormont',
    name: 'Lormont',
    postalCode: '33310',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 23500,
  },
  {
    slug: 'floirac',
    name: 'Floirac',
    postalCode: '33270',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 17350,
  },
  {
    slug: 'eysines',
    name: 'Eysines',
    postalCode: '33320',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 24200,
  },
  {
    slug: 'le-haillan',
    name: 'Le Haillan',
    postalCode: '33185',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 11250,
  },
  {
    slug: 'saint-medard-en-jalles',
    name: 'Saint-Médard-en-Jalles',
    postalCode: '33160',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 31550,
  },
  {
    slug: 'gujan-mestras',
    name: 'Gujan-Mestras',
    postalCode: '33470',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 21750,
  },
  {
    slug: 'andernos-les-bains',
    name: 'Andernos-les-Bains',
    postalCode: '33510',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 12200,
  },
  {
    slug: 'blanquefort',
    name: 'Blanquefort',
    postalCode: '33290',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 17480,
  },
  {
    slug: 'ambares-et-lagrave',
    name: 'Ambarès-et-Lagrave',
    postalCode: '33440',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 16330,
  },
  {
    slug: 'salles',
    name: 'Salles',
    postalCode: '33770',
    dept: '33',
    region: 'nouvelle-aquitaine',
    population: 7000,
  },

  // ─── Bloc 6 : Bretagne ───────────────────────────────────────────────────
  {
    slug: 'fougeres',
    name: 'Fougères',
    postalCode: '35300',
    dept: '35',
    region: 'bretagne',
    population: 20580,
  },
  {
    slug: 'vitre',
    name: 'Vitré',
    postalCode: '35500',
    dept: '35',
    region: 'bretagne',
    population: 18170,
  },
  {
    slug: 'redon',
    name: 'Redon',
    postalCode: '35600',
    dept: '35',
    region: 'bretagne',
    population: 9450,
  },
  {
    slug: 'bruz',
    name: 'Bruz',
    postalCode: '35170',
    dept: '35',
    region: 'bretagne',
    population: 18000,
  },
  {
    slug: 'cesson-sevigne',
    name: 'Cesson-Sévigné',
    postalCode: '35510',
    dept: '35',
    region: 'bretagne',
    population: 18950,
  },
  {
    slug: 'pace',
    name: 'Pacé',
    postalCode: '35740',
    dept: '35',
    region: 'bretagne',
    population: 11750,
  },
  {
    slug: 'dinan',
    name: 'Dinan',
    postalCode: '22100',
    dept: '22',
    region: 'bretagne',
    population: 14730,
  },
  {
    slug: 'lannion',
    name: 'Lannion',
    postalCode: '22300',
    dept: '22',
    region: 'bretagne',
    population: 19840,
  },
  {
    slug: 'plerin',
    name: 'Plérin',
    postalCode: '22190',
    dept: '22',
    region: 'bretagne',
    population: 14130,
  },
  {
    slug: 'lamballe-armor',
    name: 'Lamballe-Armor',
    postalCode: '22400',
    dept: '22',
    region: 'bretagne',
    population: 16370,
  },
  {
    slug: 'guingamp',
    name: 'Guingamp',
    postalCode: '22200',
    dept: '22',
    region: 'bretagne',
    population: 6800,
  },
  {
    slug: 'concarneau',
    name: 'Concarneau',
    postalCode: '29900',
    dept: '29',
    region: 'bretagne',
    population: 18900,
  },
  {
    slug: 'douarnenez',
    name: 'Douarnenez',
    postalCode: '29100',
    dept: '29',
    region: 'bretagne',
    population: 14000,
  },
  {
    slug: 'landerneau',
    name: 'Landerneau',
    postalCode: '29800',
    dept: '29',
    region: 'bretagne',
    population: 16400,
  },
  {
    slug: 'plouzane',
    name: 'Plouzané',
    postalCode: '29280',
    dept: '29',
    region: 'bretagne',
    population: 12260,
  },
  {
    slug: 'guipavas',
    name: 'Guipavas',
    postalCode: '29490',
    dept: '29',
    region: 'bretagne',
    population: 14500,
  },
  {
    slug: 'pont-l-abbe',
    name: "Pont-l'Abbé",
    postalCode: '29120',
    dept: '29',
    region: 'bretagne',
    population: 8650,
  },
  {
    slug: 'auray',
    name: 'Auray',
    postalCode: '56400',
    dept: '56',
    region: 'bretagne',
    population: 14300,
  },
  {
    slug: 'pontivy',
    name: 'Pontivy',
    postalCode: '56300',
    dept: '56',
    region: 'bretagne',
    population: 14160,
  },
  {
    slug: 'lanester',
    name: 'Lanester',
    postalCode: '56600',
    dept: '56',
    region: 'bretagne',
    population: 22550,
  },
  {
    slug: 'plouay',
    name: 'Plouay',
    postalCode: '56240',
    dept: '56',
    region: 'bretagne',
    population: 5670,
  },
  {
    slug: 'guidel',
    name: 'Guidel',
    postalCode: '56520',
    dept: '56',
    region: 'bretagne',
    population: 11900,
  },
  {
    slug: 'hennebont',
    name: 'Hennebont',
    postalCode: '56700',
    dept: '56',
    region: 'bretagne',
    population: 16100,
  },

  // ─── Bloc 7 : Pays de la Loire ──────────────────────────────────────────
  {
    slug: 'la-chapelle-sur-erdre',
    name: 'La Chapelle-sur-Erdre',
    postalCode: '44240',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 19850,
  },
  {
    slug: 'orvault',
    name: 'Orvault',
    postalCode: '44700',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 26980,
  },
  {
    slug: 'saint-herblain',
    name: 'Saint-Herblain',
    postalCode: '44800',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 47800,
  },
  {
    slug: 'vertou',
    name: 'Vertou',
    postalCode: '44120',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 25300,
  },
  {
    slug: 'coueron',
    name: 'Couëron',
    postalCode: '44220',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 22950,
  },
  {
    slug: 'bouguenais',
    name: 'Bouguenais',
    postalCode: '44340',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 19700,
  },
  {
    slug: 'pornic',
    name: 'Pornic',
    postalCode: '44210',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 16200,
  },
  {
    slug: 'guerande',
    name: 'Guérande',
    postalCode: '44350',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 16700,
  },
  {
    slug: 'ancenis-saint-gereon',
    name: 'Ancenis-Saint-Géréon',
    postalCode: '44150',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 11400,
  },
  {
    slug: 'chateaubriant',
    name: 'Châteaubriant',
    postalCode: '44110',
    dept: '44',
    region: 'pays-de-la-loire',
    population: 13050,
  },
  {
    slug: 'beaupreau-en-mauges',
    name: 'Beaupréau-en-Mauges',
    postalCode: '49600',
    dept: '49',
    region: 'pays-de-la-loire',
    population: 23150,
  },
  {
    slug: 'avrille',
    name: 'Avrillé',
    postalCode: '49240',
    dept: '49',
    region: 'pays-de-la-loire',
    population: 14250,
  },
  {
    slug: 'les-ponts-de-ce',
    name: 'Les Ponts-de-Cé',
    postalCode: '49130',
    dept: '49',
    region: 'pays-de-la-loire',
    population: 12550,
  },
  {
    slug: 'mayenne',
    name: 'Mayenne',
    postalCode: '53100',
    dept: '53',
    region: 'pays-de-la-loire',
    population: 13350,
  },
  {
    slug: 'chateau-gontier',
    name: 'Château-Gontier',
    postalCode: '53200',
    dept: '53',
    region: 'pays-de-la-loire',
    population: 11900,
  },
  {
    slug: 'sable-sur-sarthe',
    name: 'Sablé-sur-Sarthe',
    postalCode: '72300',
    dept: '72',
    region: 'pays-de-la-loire',
    population: 12450,
  },
  {
    slug: 'la-fleche',
    name: 'La Flèche',
    postalCode: '72200',
    dept: '72',
    region: 'pays-de-la-loire',
    population: 14550,
  },
  {
    slug: 'fontenay-le-comte',
    name: 'Fontenay-le-Comte',
    postalCode: '85200',
    dept: '85',
    region: 'pays-de-la-loire',
    population: 13900,
  },
  {
    slug: 'challans',
    name: 'Challans',
    postalCode: '85300',
    dept: '85',
    region: 'pays-de-la-loire',
    population: 21070,
  },
  {
    slug: 'olonne-sur-mer',
    name: 'Olonne-sur-Mer',
    postalCode: '85340',
    dept: '85',
    region: 'pays-de-la-loire',
    population: 14900,
  },

  // ─── Bloc 8 : Normandie ─────────────────────────────────────────────────
  {
    slug: 'mondeville',
    name: 'Mondeville',
    postalCode: '14120',
    dept: '14',
    region: 'normandie',
    population: 9450,
  },
  {
    slug: 'herouville-saint-clair',
    name: 'Hérouville-Saint-Clair',
    postalCode: '14200',
    dept: '14',
    region: 'normandie',
    population: 21380,
  },
  {
    slug: 'ifs',
    name: 'Ifs',
    postalCode: '14123',
    dept: '14',
    region: 'normandie',
    population: 12200,
  },
  {
    slug: 'bayeux',
    name: 'Bayeux',
    postalCode: '14400',
    dept: '14',
    region: 'normandie',
    population: 13150,
  },
  {
    slug: 'vire-normandie',
    name: 'Vire-Normandie',
    postalCode: '14500',
    dept: '14',
    region: 'normandie',
    population: 17390,
  },
  {
    slug: 'deauville',
    name: 'Deauville',
    postalCode: '14800',
    dept: '14',
    region: 'normandie',
    population: 3800,
  },
  {
    slug: 'trouville-sur-mer',
    name: 'Trouville-sur-Mer',
    postalCode: '14360',
    dept: '14',
    region: 'normandie',
    population: 4720,
  },
  {
    slug: 'falaise',
    name: 'Falaise',
    postalCode: '14700',
    dept: '14',
    region: 'normandie',
    population: 8030,
  },
  {
    slug: 'sotteville-les-rouen',
    name: 'Sotteville-lès-Rouen',
    postalCode: '76300',
    dept: '76',
    region: 'normandie',
    population: 28630,
  },
  {
    slug: 'le-petit-quevilly',
    name: 'Le Petit-Quevilly',
    postalCode: '76140',
    dept: '76',
    region: 'normandie',
    population: 22420,
  },
  {
    slug: 'mont-saint-aignan',
    name: 'Mont-Saint-Aignan',
    postalCode: '76130',
    dept: '76',
    region: 'normandie',
    population: 19900,
  },
  {
    slug: 'bois-guillaume',
    name: 'Bois-Guillaume',
    postalCode: '76230',
    dept: '76',
    region: 'normandie',
    population: 13420,
  },
  {
    slug: 'darnetal',
    name: 'Darnétal',
    postalCode: '76160',
    dept: '76',
    region: 'normandie',
    population: 9430,
  },
  {
    slug: 'oissel',
    name: 'Oissel',
    postalCode: '76350',
    dept: '76',
    region: 'normandie',
    population: 12180,
  },
  {
    slug: 'maromme',
    name: 'Maromme',
    postalCode: '76150',
    dept: '76',
    region: 'normandie',
    population: 11150,
  },
  {
    slug: 'elbeuf',
    name: 'Elbeuf',
    postalCode: '76500',
    dept: '76',
    region: 'normandie',
    population: 17100,
  },
  {
    slug: 'le-grand-quevilly',
    name: 'Le Grand-Quevilly',
    postalCode: '76120',
    dept: '76',
    region: 'normandie',
    population: 25800,
  },
  {
    slug: 'pont-audemer',
    name: 'Pont-Audemer',
    postalCode: '27500',
    dept: '27',
    region: 'normandie',
    population: 9070,
  },
  {
    slug: 'louviers',
    name: 'Louviers',
    postalCode: '27400',
    dept: '27',
    region: 'normandie',
    population: 18650,
  },
  {
    slug: 'val-de-reuil',
    name: 'Val-de-Reuil',
    postalCode: '27100',
    dept: '27',
    region: 'normandie',
    population: 13900,
  },
  {
    slug: 'vernon',
    name: 'Vernon',
    postalCode: '27200',
    dept: '27',
    region: 'normandie',
    population: 24050,
  },
  {
    slug: 'gisors',
    name: 'Gisors',
    postalCode: '27140',
    dept: '27',
    region: 'normandie',
    population: 11650,
  },
  {
    slug: 'argentan',
    name: 'Argentan',
    postalCode: '61200',
    dept: '61',
    region: 'normandie',
    population: 13770,
  },
  {
    slug: 'flers',
    name: 'Flers',
    postalCode: '61100',
    dept: '61',
    region: 'normandie',
    population: 14250,
  },
  {
    slug: 'avranches',
    name: 'Avranches',
    postalCode: '50300',
    dept: '50',
    region: 'normandie',
    population: 8120,
  },
  {
    slug: 'granville',
    name: 'Granville',
    postalCode: '50400',
    dept: '50',
    region: 'normandie',
    population: 12600,
  },
  {
    slug: 'coutances',
    name: 'Coutances',
    postalCode: '50200',
    dept: '50',
    region: 'normandie',
    population: 8830,
  },

  // ─── Bloc 9 : Hauts-de-France ───────────────────────────────────────────
  {
    slug: 'wattrelos',
    name: 'Wattrelos',
    postalCode: '59150',
    dept: '59',
    region: 'hauts-de-france',
    population: 40800,
  },
  {
    slug: 'maubeuge',
    name: 'Maubeuge',
    postalCode: '59600',
    dept: '59',
    region: 'hauts-de-france',
    population: 30150,
  },
  {
    slug: 'denain',
    name: 'Denain',
    postalCode: '59220',
    dept: '59',
    region: 'hauts-de-france',
    population: 20120,
  },
  {
    slug: 'wattignies',
    name: 'Wattignies',
    postalCode: '59139',
    dept: '59',
    region: 'hauts-de-france',
    population: 14400,
  },
  {
    slug: 'marcq-en-baroeul',
    name: 'Marcq-en-Barœul',
    postalCode: '59700',
    dept: '59',
    region: 'hauts-de-france',
    population: 39600,
  },
  {
    slug: 'mons-en-baroeul',
    name: 'Mons-en-Barœul',
    postalCode: '59370',
    dept: '59',
    region: 'hauts-de-france',
    population: 21750,
  },
  {
    slug: 'lambersart',
    name: 'Lambersart',
    postalCode: '59130',
    dept: '59',
    region: 'hauts-de-france',
    population: 28400,
  },
  {
    slug: 'la-madeleine',
    name: 'La Madeleine',
    postalCode: '59110',
    dept: '59',
    region: 'hauts-de-france',
    population: 22100,
  },
  {
    slug: 'croix',
    name: 'Croix',
    postalCode: '59170',
    dept: '59',
    region: 'hauts-de-france',
    population: 21100,
  },
  {
    slug: 'wasquehal',
    name: 'Wasquehal',
    postalCode: '59290',
    dept: '59',
    region: 'hauts-de-france',
    population: 20850,
  },
  {
    slug: 'haubourdin',
    name: 'Haubourdin',
    postalCode: '59320',
    dept: '59',
    region: 'hauts-de-france',
    population: 14750,
  },
  {
    slug: 'armentieres',
    name: 'Armentières',
    postalCode: '59280',
    dept: '59',
    region: 'hauts-de-france',
    population: 25340,
  },
  {
    slug: 'halluin',
    name: 'Halluin',
    postalCode: '59250',
    dept: '59',
    region: 'hauts-de-france',
    population: 20650,
  },
  {
    slug: 'somain',
    name: 'Somain',
    postalCode: '59490',
    dept: '59',
    region: 'hauts-de-france',
    population: 12550,
  },
  {
    slug: 'aniche',
    name: 'Aniche',
    postalCode: '59580',
    dept: '59',
    region: 'hauts-de-france',
    population: 9970,
  },
  {
    slug: 'lievin',
    name: 'Liévin',
    postalCode: '62800',
    dept: '62',
    region: 'hauts-de-france',
    population: 30680,
  },
  {
    slug: 'henin-beaumont',
    name: 'Hénin-Beaumont',
    postalCode: '62110',
    dept: '62',
    region: 'hauts-de-france',
    population: 26500,
  },
  {
    slug: 'bethune',
    name: 'Béthune',
    postalCode: '62400',
    dept: '62',
    region: 'hauts-de-france',
    population: 24700,
  },
  {
    slug: 'bruay-la-buissiere',
    name: 'Bruay-la-Buissière',
    postalCode: '62700',
    dept: '62',
    region: 'hauts-de-france',
    population: 22050,
  },
  {
    slug: 'noyon',
    name: 'Noyon',
    postalCode: '60400',
    dept: '60',
    region: 'hauts-de-france',
    population: 13580,
  },
  {
    slug: 'creil',
    name: 'Creil',
    postalCode: '60100',
    dept: '60',
    region: 'hauts-de-france',
    population: 35400,
  },
  {
    slug: 'senlis',
    name: 'Senlis',
    postalCode: '60300',
    dept: '60',
    region: 'hauts-de-france',
    population: 15500,
  },
  {
    slug: 'pont-sainte-maxence',
    name: 'Pont-Sainte-Maxence',
    postalCode: '60700',
    dept: '60',
    region: 'hauts-de-france',
    population: 12880,
  },
  {
    slug: 'chantilly',
    name: 'Chantilly',
    postalCode: '60500',
    dept: '60',
    region: 'hauts-de-france',
    population: 10920,
  },
  {
    slug: 'longueau',
    name: 'Longueau',
    postalCode: '80330',
    dept: '80',
    region: 'hauts-de-france',
    population: 5530,
  },
  {
    slug: 'tergnier',
    name: 'Tergnier',
    postalCode: '02700',
    dept: '02',
    region: 'hauts-de-france',
    population: 13600,
  },
  {
    slug: 'laon',
    name: 'Laon',
    postalCode: '02000',
    dept: '02',
    region: 'hauts-de-france',
    population: 24230,
  },
  {
    slug: 'chauny',
    name: 'Chauny',
    postalCode: '02300',
    dept: '02',
    region: 'hauts-de-france',
    population: 12090,
  },
  {
    slug: 'hirson',
    name: 'Hirson',
    postalCode: '02500',
    dept: '02',
    region: 'hauts-de-france',
    population: 8740,
  },

  // ─── Bloc 10 : Grand Est ────────────────────────────────────────────────
  {
    slug: 'schiltigheim',
    name: 'Schiltigheim',
    postalCode: '67300',
    dept: '67',
    region: 'grand-est',
    population: 33150,
  },
  {
    slug: 'illkirch-graffenstaden',
    name: 'Illkirch-Graffenstaden',
    postalCode: '67400',
    dept: '67',
    region: 'grand-est',
    population: 26890,
  },
  {
    slug: 'lingolsheim',
    name: 'Lingolsheim',
    postalCode: '67380',
    dept: '67',
    region: 'grand-est',
    population: 18200,
  },
  {
    slug: 'bischheim',
    name: 'Bischheim',
    postalCode: '67800',
    dept: '67',
    region: 'grand-est',
    population: 18180,
  },
  {
    slug: 'hoenheim',
    name: 'Hœnheim',
    postalCode: '67800',
    dept: '67',
    region: 'grand-est',
    population: 11580,
  },
  {
    slug: 'ostwald',
    name: 'Ostwald',
    postalCode: '67540',
    dept: '67',
    region: 'grand-est',
    population: 13380,
  },
  {
    slug: 'wissembourg',
    name: 'Wissembourg',
    postalCode: '67160',
    dept: '67',
    region: 'grand-est',
    population: 8050,
  },
  {
    slug: 'molsheim',
    name: 'Molsheim',
    postalCode: '67120',
    dept: '67',
    region: 'grand-est',
    population: 9420,
  },
  {
    slug: 'saverne',
    name: 'Saverne',
    postalCode: '67700',
    dept: '67',
    region: 'grand-est',
    population: 11860,
  },
  {
    slug: 'obernai',
    name: 'Obernai',
    postalCode: '67210',
    dept: '67',
    region: 'grand-est',
    population: 11580,
  },
  {
    slug: 'kingersheim',
    name: 'Kingersheim',
    postalCode: '68260',
    dept: '68',
    region: 'grand-est',
    population: 13290,
  },
  {
    slug: 'illzach',
    name: 'Illzach',
    postalCode: '68110',
    dept: '68',
    region: 'grand-est',
    population: 14750,
  },
  {
    slug: 'wittenheim',
    name: 'Wittenheim',
    postalCode: '68270',
    dept: '68',
    region: 'grand-est',
    population: 14700,
  },
  {
    slug: 'rixheim',
    name: 'Rixheim',
    postalCode: '68170',
    dept: '68',
    region: 'grand-est',
    population: 13800,
  },
  {
    slug: 'guebwiller',
    name: 'Guebwiller',
    postalCode: '68500',
    dept: '68',
    region: 'grand-est',
    population: 11240,
  },
  {
    slug: 'cernay',
    name: 'Cernay',
    postalCode: '68700',
    dept: '68',
    region: 'grand-est',
    population: 11400,
  },
  {
    slug: 'saint-louis',
    name: 'Saint-Louis',
    postalCode: '68300',
    dept: '68',
    region: 'grand-est',
    population: 21500,
  },
  {
    slug: 'sarrebourg',
    name: 'Sarrebourg',
    postalCode: '57400',
    dept: '57',
    region: 'grand-est',
    population: 12230,
  },
  {
    slug: 'sarreguemines',
    name: 'Sarreguemines',
    postalCode: '57200',
    dept: '57',
    region: 'grand-est',
    population: 21260,
  },
  {
    slug: 'creutzwald',
    name: 'Creutzwald',
    postalCode: '57150',
    dept: '57',
    region: 'grand-est',
    population: 13700,
  },
  {
    slug: 'hagondange',
    name: 'Hagondange',
    postalCode: '57300',
    dept: '57',
    region: 'grand-est',
    population: 9090,
  },
  {
    slug: 'maizieres-les-metz',
    name: 'Maizières-lès-Metz',
    postalCode: '57280',
    dept: '57',
    region: 'grand-est',
    population: 11030,
  },
  {
    slug: 'montigny-les-metz',
    name: 'Montigny-lès-Metz',
    postalCode: '57950',
    dept: '57',
    region: 'grand-est',
    population: 21420,
  },
  {
    slug: 'jarny',
    name: 'Jarny',
    postalCode: '54800',
    dept: '54',
    region: 'grand-est',
    population: 8270,
  },
  {
    slug: 'longwy',
    name: 'Longwy',
    postalCode: '54400',
    dept: '54',
    region: 'grand-est',
    population: 14250,
  },
  {
    slug: 'pont-a-mousson',
    name: 'Pont-à-Mousson',
    postalCode: '54700',
    dept: '54',
    region: 'grand-est',
    population: 14550,
  },
  {
    slug: 'toul',
    name: 'Toul',
    postalCode: '54200',
    dept: '54',
    region: 'grand-est',
    population: 15850,
  },
  {
    slug: 'vandoeuvre-les-nancy',
    name: 'Vandœuvre-lès-Nancy',
    postalCode: '54500',
    dept: '54',
    region: 'grand-est',
    population: 29920,
  },
  {
    slug: 'saint-die-des-vosges',
    name: 'Saint-Dié-des-Vosges',
    postalCode: '88100',
    dept: '88',
    region: 'grand-est',
    population: 19440,
  },
  {
    slug: 'remiremont',
    name: 'Remiremont',
    postalCode: '88200',
    dept: '88',
    region: 'grand-est',
    population: 7700,
  },
  {
    slug: 'gerardmer',
    name: 'Gérardmer',
    postalCode: '88400',
    dept: '88',
    region: 'grand-est',
    population: 7950,
  },
  {
    slug: 'sedan',
    name: 'Sedan',
    postalCode: '08200',
    dept: '08',
    region: 'grand-est',
    population: 16400,
  },
  {
    slug: 'charleville-mezieres',
    name: 'Charleville-Mézières',
    postalCode: '08000',
    dept: '08',
    region: 'grand-est',
    population: 46330,
  },
  {
    slug: 'chaumont',
    name: 'Chaumont',
    postalCode: '52000',
    dept: '52',
    region: 'grand-est',
    population: 21630,
  },
  {
    slug: 'saint-dizier',
    name: 'Saint-Dizier',
    postalCode: '52100',
    dept: '52',
    region: 'grand-est',
    population: 24530,
  },
  {
    slug: 'romilly-sur-seine',
    name: 'Romilly-sur-Seine',
    postalCode: '10100',
    dept: '10',
    region: 'grand-est',
    population: 13770,
  },
  {
    slug: 'bar-sur-aube',
    name: 'Bar-sur-Aube',
    postalCode: '10200',
    dept: '10',
    region: 'grand-est',
    population: 5050,
  },

  // ─── Bloc 11 : Bourgogne-Franche-Comté ──────────────────────────────────
  {
    slug: 'pontailler-sur-saone',
    name: 'Pontailler-sur-Saône',
    postalCode: '21270',
    dept: '21',
    region: 'bourgogne-franche-comte',
    population: 1430,
  },
  {
    slug: 'talant',
    name: 'Talant',
    postalCode: '21240',
    dept: '21',
    region: 'bourgogne-franche-comte',
    population: 11220,
  },
  {
    slug: 'chenove',
    name: 'Chenôve',
    postalCode: '21300',
    dept: '21',
    region: 'bourgogne-franche-comte',
    population: 13980,
  },
  {
    slug: 'le-creusot',
    name: 'Le Creusot',
    postalCode: '71200',
    dept: '71',
    region: 'bourgogne-franche-comte',
    population: 21450,
  },
  {
    slug: 'autun',
    name: 'Autun',
    postalCode: '71400',
    dept: '71',
    region: 'bourgogne-franche-comte',
    population: 12930,
  },
  {
    slug: 'montceau-les-mines',
    name: 'Montceau-les-Mines',
    postalCode: '71300',
    dept: '71',
    region: 'bourgogne-franche-comte',
    population: 17700,
  },
  {
    slug: 'paray-le-monial',
    name: 'Paray-le-Monial',
    postalCode: '71600',
    dept: '71',
    region: 'bourgogne-franche-comte',
    population: 9170,
  },
  {
    slug: 'cosne-cours-sur-loire',
    name: 'Cosne-Cours-sur-Loire',
    postalCode: '58200',
    dept: '58',
    region: 'bourgogne-franche-comte',
    population: 10100,
  },
  {
    slug: 'avallon',
    name: 'Avallon',
    postalCode: '89200',
    dept: '89',
    region: 'bourgogne-franche-comte',
    population: 6700,
  },
  {
    slug: 'joigny',
    name: 'Joigny',
    postalCode: '89300',
    dept: '89',
    region: 'bourgogne-franche-comte',
    population: 9710,
  },
  {
    slug: 'audincourt',
    name: 'Audincourt',
    postalCode: '25400',
    dept: '25',
    region: 'bourgogne-franche-comte',
    population: 14100,
  },
  {
    slug: 'valentigney',
    name: 'Valentigney',
    postalCode: '25700',
    dept: '25',
    region: 'bourgogne-franche-comte',
    population: 11050,
  },
  {
    slug: 'dole',
    name: 'Dole',
    postalCode: '39100',
    dept: '39',
    region: 'bourgogne-franche-comte',
    population: 23330,
  },
  {
    slug: 'saint-claude',
    name: 'Saint-Claude',
    postalCode: '39200',
    dept: '39',
    region: 'bourgogne-franche-comte',
    population: 9400,
  },
  {
    slug: 'gray',
    name: 'Gray',
    postalCode: '70100',
    dept: '70',
    region: 'bourgogne-franche-comte',
    population: 5500,
  },
  {
    slug: 'lure',
    name: 'Lure',
    postalCode: '70200',
    dept: '70',
    region: 'bourgogne-franche-comte',
    population: 7950,
  },
  {
    slug: 'luxeuil-les-bains',
    name: 'Luxeuil-les-Bains',
    postalCode: '70300',
    dept: '70',
    region: 'bourgogne-franche-comte',
    population: 6680,
  },

  // ─── Bloc 12 : Centre-Val de Loire ──────────────────────────────────────
  {
    slug: 'fleury-les-aubrais',
    name: 'Fleury-les-Aubrais',
    postalCode: '45400',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 21770,
  },
  {
    slug: 'olivet',
    name: 'Olivet',
    postalCode: '45160',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 22150,
  },
  {
    slug: 'saint-jean-de-la-ruelle',
    name: 'Saint-Jean-de-la-Ruelle',
    postalCode: '45140',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 16550,
  },
  {
    slug: 'saran',
    name: 'Saran',
    postalCode: '45770',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 16450,
  },
  {
    slug: 'gien',
    name: 'Gien',
    postalCode: '45500',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 14060,
  },
  {
    slug: 'pithiviers',
    name: 'Pithiviers',
    postalCode: '45300',
    dept: '45',
    region: 'centre-val-de-loire',
    population: 9270,
  },
  {
    slug: 'amboise',
    name: 'Amboise',
    postalCode: '37400',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 13360,
  },
  {
    slug: 'joue-les-tours',
    name: 'Joué-lès-Tours',
    postalCode: '37300',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 39230,
  },
  {
    slug: 'saint-pierre-des-corps',
    name: 'Saint-Pierre-des-Corps',
    postalCode: '37700',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 16650,
  },
  {
    slug: 'saint-cyr-sur-loire',
    name: 'Saint-Cyr-sur-Loire',
    postalCode: '37540',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 16560,
  },
  {
    slug: 'chinon',
    name: 'Chinon',
    postalCode: '37500',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 7960,
  },
  {
    slug: 'loches',
    name: 'Loches',
    postalCode: '37600',
    dept: '37',
    region: 'centre-val-de-loire',
    population: 6680,
  },
  {
    slug: 'vendome',
    name: 'Vendôme',
    postalCode: '41100',
    dept: '41',
    region: 'centre-val-de-loire',
    population: 16550,
  },
  {
    slug: 'romorantin-lanthenay',
    name: 'Romorantin-Lanthenay',
    postalCode: '41200',
    dept: '41',
    region: 'centre-val-de-loire',
    population: 16930,
  },
  {
    slug: 'lucon',
    name: 'Luçon',
    postalCode: '85400',
    dept: '85',
    region: 'pays-de-la-loire',
    population: 9560,
  },
  {
    slug: 'dreux',
    name: 'Dreux',
    postalCode: '28100',
    dept: '28',
    region: 'centre-val-de-loire',
    population: 31700,
  },
  {
    slug: 'luce',
    name: 'Lucé',
    postalCode: '28110',
    dept: '28',
    region: 'centre-val-de-loire',
    population: 16800,
  },
  {
    slug: 'mainvilliers',
    name: 'Mainvilliers',
    postalCode: '28300',
    dept: '28',
    region: 'centre-val-de-loire',
    population: 10670,
  },
  {
    slug: 'chateaudun',
    name: 'Châteaudun',
    postalCode: '28200',
    dept: '28',
    region: 'centre-val-de-loire',
    population: 13150,
  },
  {
    slug: 'vierzon',
    name: 'Vierzon',
    postalCode: '18100',
    dept: '18',
    region: 'centre-val-de-loire',
    population: 26400,
  },
  {
    slug: 'saint-amand-montrond',
    name: 'Saint-Amand-Montrond',
    postalCode: '18200',
    dept: '18',
    region: 'centre-val-de-loire',
    population: 10400,
  },
  {
    slug: 'issoudun',
    name: 'Issoudun',
    postalCode: '36100',
    dept: '36',
    region: 'centre-val-de-loire',
    population: 11750,
  },
  {
    slug: 'argenton-sur-creuse',
    name: 'Argenton-sur-Creuse',
    postalCode: '36200',
    dept: '36',
    region: 'centre-val-de-loire',
    population: 4830,
  },

  // ─── Bloc 13 : Corse + DROM ─────────────────────────────────────────────
  {
    slug: 'ajaccio',
    name: 'Ajaccio',
    postalCode: '20000',
    dept: '2A',
    region: 'corse',
    population: 71361,
  },
  {
    slug: 'bastia',
    name: 'Bastia',
    postalCode: '20200',
    dept: '2B',
    region: 'corse',
    population: 48226,
  },
  {
    slug: 'porto-vecchio',
    name: 'Porto-Vecchio',
    postalCode: '20137',
    dept: '2A',
    region: 'corse',
    population: 12110,
  },
  {
    slug: 'corte',
    name: 'Corte',
    postalCode: '20250',
    dept: '2B',
    region: 'corse',
    population: 7437,
  },
  {
    slug: 'sartene',
    name: 'Sartène',
    postalCode: '20100',
    dept: '2A',
    region: 'corse',
    population: 3320,
  },
  {
    slug: 'calvi',
    name: 'Calvi',
    postalCode: '20260',
    dept: '2B',
    region: 'corse',
    population: 5670,
  },
  {
    slug: 'pointe-a-pitre',
    name: 'Pointe-à-Pitre',
    postalCode: '97110',
    dept: '971',
    region: 'guadeloupe',
    population: 14794,
  },
  {
    slug: 'les-abymes',
    name: 'Les Abymes',
    postalCode: '97142',
    dept: '971',
    region: 'guadeloupe',
    population: 51710,
  },
  {
    slug: 'basse-terre',
    name: 'Basse-Terre',
    postalCode: '97100',
    dept: '971',
    region: 'guadeloupe',
    population: 9800,
  },
  {
    slug: 'le-gosier',
    name: 'Le Gosier',
    postalCode: '97190',
    dept: '971',
    region: 'guadeloupe',
    population: 26780,
  },
  {
    slug: 'baie-mahault',
    name: 'Baie-Mahault',
    postalCode: '97122',
    dept: '971',
    region: 'guadeloupe',
    population: 30650,
  },
  {
    slug: 'le-moule',
    name: 'Le Moule',
    postalCode: '97160',
    dept: '971',
    region: 'guadeloupe',
    population: 21330,
  },
  {
    slug: 'sainte-anne-guadeloupe',
    name: 'Sainte-Anne (Guadeloupe)',
    postalCode: '97180',
    dept: '971',
    region: 'guadeloupe',
    population: 24330,
  },
  {
    slug: 'petit-bourg',
    name: 'Petit-Bourg',
    postalCode: '97170',
    dept: '971',
    region: 'guadeloupe',
    population: 25080,
  },
  {
    slug: 'sainte-rose-guadeloupe',
    name: 'Sainte-Rose (Guadeloupe)',
    postalCode: '97115',
    dept: '971',
    region: 'guadeloupe',
    population: 18510,
  },
  {
    slug: 'morne-a-l-eau',
    name: "Morne-à-l'Eau",
    postalCode: '97111',
    dept: '971',
    region: 'guadeloupe',
    population: 16730,
  },
  {
    slug: 'le-robert',
    name: 'Le Robert',
    postalCode: '97231',
    dept: '972',
    region: 'martinique',
    population: 22650,
  },
  {
    slug: 'sainte-marie-martinique',
    name: 'Sainte-Marie (Martinique)',
    postalCode: '97230',
    dept: '972',
    region: 'martinique',
    population: 16400,
  },
  {
    slug: 'le-francois',
    name: 'Le François',
    postalCode: '97240',
    dept: '972',
    region: 'martinique',
    population: 17730,
  },
  {
    slug: 'cayenne',
    name: 'Cayenne',
    postalCode: '97300',
    dept: '973',
    region: 'guyane',
    population: 65493,
  },
  {
    slug: 'matoury',
    name: 'Matoury',
    postalCode: '97351',
    dept: '973',
    region: 'guyane',
    population: 35150,
  },
  {
    slug: 'kourou',
    name: 'Kourou',
    postalCode: '97310',
    dept: '973',
    region: 'guyane',
    population: 25490,
  },
  {
    slug: 'saint-laurent-du-maroni',
    name: 'Saint-Laurent-du-Maroni',
    postalCode: '97320',
    dept: '973',
    region: 'guyane',
    population: 49620,
  },
  {
    slug: 'saint-denis-reunion',
    name: 'Saint-Denis (La Réunion)',
    postalCode: '97400',
    dept: '974',
    region: 'la-reunion',
    population: 153810,
  },
  {
    slug: 'saint-paul-reunion',
    name: 'Saint-Paul (La Réunion)',
    postalCode: '97460',
    dept: '974',
    region: 'la-reunion',
    population: 105230,
  },
  {
    slug: 'saint-pierre-reunion',
    name: 'Saint-Pierre (La Réunion)',
    postalCode: '97410',
    dept: '974',
    region: 'la-reunion',
    population: 86230,
  },
  {
    slug: 'le-tampon',
    name: 'Le Tampon',
    postalCode: '97430',
    dept: '974',
    region: 'la-reunion',
    population: 80300,
  },
  {
    slug: 'saint-andre-reunion',
    name: 'Saint-André (La Réunion)',
    postalCode: '97440',
    dept: '974',
    region: 'la-reunion',
    population: 56010,
  },
  {
    slug: 'saint-louis-reunion',
    name: 'Saint-Louis (La Réunion)',
    postalCode: '97450',
    dept: '974',
    region: 'la-reunion',
    population: 52830,
  },
  {
    slug: 'le-port-reunion',
    name: 'Le Port (La Réunion)',
    postalCode: '97420',
    dept: '974',
    region: 'la-reunion',
    population: 33970,
  },
  {
    slug: 'mamoudzou',
    name: 'Mamoudzou',
    postalCode: '97600',
    dept: '976',
    region: 'mayotte',
    population: 71437,
  },
  {
    slug: 'koungou',
    name: 'Koungou',
    postalCode: '97600',
    dept: '976',
    region: 'mayotte',
    population: 32156,
  },
  {
    slug: 'dzaoudzi',
    name: 'Dzaoudzi',
    postalCode: '97615',
    dept: '976',
    region: 'mayotte',
    population: 17680,
  },
]

/**
 * Helpers — lookup unifié sur registry + extras.
 */
const EXTRAS_BY_SLUG: ReadonlyMap<string, ExtraCity> = new Map(
  EXTRA_CITIES_TOP_5000.map((c) => [c.slug, c]),
)

/**
 * Trouve une ville (City complète) dans le registry OU dans les extras top-5000.
 * Retourne undefined si introuvable.
 */
export function findCityAnywhere(slug: string): City | undefined {
  const direct = getCityBySlug(slug)
  if (direct) return direct
  const extra = EXTRAS_BY_SLUG.get(slug)
  if (!extra) return undefined
  return extraToCity(extra)
}

/**
 * Tous les slugs des villes premium + extras (utilisé par generateStaticParams).
 * Garantit l'unicité (set deduplication).
 */
export function getAllTop5000Slugs(): ReadonlyArray<{ dept: string; city: string }> {
  const set = new Set<string>()
  const out: Array<{ dept: string; city: string }> = []
  for (const c of CITIES) {
    const key = `${c.dept}:${c.slug}`
    if (!set.has(key)) {
      set.add(key)
      out.push({ dept: c.dept, city: c.slug })
    }
  }
  for (const c of EXTRA_CITIES_TOP_5000) {
    const key = `${c.dept}:${c.slug}`
    if (!set.has(key)) {
      set.add(key)
      out.push({ dept: c.dept, city: c.slug })
    }
  }
  return out
}

/**
 * Statistiques top-5000 (registry + extras).
 */
export function getTop5000Stats(): {
  totalRegistry: number
  totalExtras: number
  totalUnique: number
  byRegion: Record<string, number>
} {
  const byRegion: Record<string, number> = {}
  const seenSlugs = new Set<string>()

  for (const c of CITIES) {
    if (seenSlugs.has(c.slug)) continue
    seenSlugs.add(c.slug)
    byRegion[c.region] = (byRegion[c.region] ?? 0) + 1
  }
  for (const c of EXTRA_CITIES_TOP_5000) {
    if (seenSlugs.has(c.slug)) continue
    seenSlugs.add(c.slug)
    byRegion[c.region] = (byRegion[c.region] ?? 0) + 1
  }

  return {
    totalRegistry: CITIES.length,
    totalExtras: EXTRA_CITIES_TOP_5000.length,
    totalUnique: seenSlugs.size,
    byRegion,
  }
}

export const DEPT_TO_REGION_MAP = DEPT_TO_REGION
export const DEPT_CAPITALS_MAP = DEPT_CAPITALS
