/**
 * Checklist Amiante (DAPP / DTA / Avant travaux).
 *
 * Périmètre métier : bien construit avant le 1er juillet 1997 — repérage
 * des matériaux et produits contenant de l'amiante (MPCA) listés en
 * annexe 13-9 du Code de la santé publique (programme A, B).
 *
 * 18 items répartis sur 5 sections : périmètre / repérage visuel /
 * prélèvements / état conservation / rapport.
 */

import { TRIGGER_DELAYS, type DiagnosticChecklist } from './types'

export const AMIANTE_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'amiante',
  short_label: 'AMIANTE',
  long_label: 'Repérage Amiante (DAPP / DTA)',
  sections: [
    {
      id: 'scope',
      label: 'Périmètre du repérage',
      items: [
        {
          id: 'amiante_pre_1997',
          field_name: 'amiante.pre_1997_check',
          description_short: 'PC déposé avant 1997',
          description_full: 'Confirmation que le permis de construire est antérieur au 1er juillet 1997 (sinon repérage non requis).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'Le permis de construire est-il bien antérieur au 1er juillet 1997 ?',
          keywords: ['1997', 'permis', 'avant 1997', 'construction', 'antérieur'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_mission_type',
          field_name: 'amiante.mission_type',
          description_short: 'Type de mission (DAPP/DTA/AT)',
          description_full: 'DAPP (parties privatives), DTA (parties communes), AT (avant travaux), AD (avant démolition).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'Quel est le type exact de la mission amiante (DAPP, DTA, avant travaux) ?',
          keywords: ['dapp', 'dta', 'avant travaux', 'amiante', 'parties privatives', 'parties communes'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_program',
          field_name: 'amiante.program_list',
          description_short: 'Programme A et B couverts',
          description_full: 'Liste A (flocages, calorifugeages, faux-plafonds) + Liste B (autres MPCA accessibles).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'La mission couvre-t-elle bien la liste A et la liste B (annexe 13-9 CSP) ?',
          keywords: ['liste a', 'liste b', 'programme', 'mpca', 'annexe 13-9'],
          diagnostic: 'amiante',
        },
      ],
    },
    {
      id: 'visual_inspection',
      label: 'Repérage visuel par pièce',
      items: [
        {
          id: 'amiante_floor_covering',
          field_name: 'amiante.floor_covering',
          description_short: 'Revêtement de sol (dalle vinyle)',
          description_full: 'Dalles vinyle/amiante 30×30 ou 50×50, colle bitume, sous-couche.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Quel est le revêtement de sol dans cette pièce ? Dalles vinyle suspectes ?',
          keywords: ['sol', 'dalle', 'vinyle', 'lino', 'linoléum', 'colle', 'carrelage', 'parquet', 'revêtement'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_wall_finishing',
          field_name: 'amiante.wall_finishing',
          description_short: 'Murs et plafond (enduit/peinture)',
          description_full: 'Enduits taloché-amiantés, peintures plastiques anciennes, mortiers colle, joints.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Quel est le revêtement des murs et plafond de cette pièce ?',
          keywords: ['mur', 'plafond', 'enduit', 'peinture', 'taloché', 'crépi', 'joint', 'mortier'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_false_ceiling',
          field_name: 'amiante.false_ceiling',
          description_short: 'Faux-plafond (dalles)',
          description_full: 'Dalles fibreuses suspectes, ossature, isolant interstitiel (programme A).',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Y a-t-il un faux-plafond ? Si oui, dalles fibreuses suspectes ?',
          keywords: ['faux plafond', 'dalle', 'plafond suspendu', 'ossature', 'fibreuse'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_flocking',
          field_name: 'amiante.flocking',
          description_short: 'Flocage (poutres, planchers)',
          description_full: 'Flocage suspect sur structure métallique / béton (programme A liste A).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Présence d\'un flocage sur structure métallique ou béton ?',
          keywords: ['flocage', 'floqué', 'projection', 'poutre', 'sous-face plancher'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_calorifuge',
          field_name: 'amiante.calorifugeage',
          description_short: 'Calorifugeage canalisations',
          description_full: 'Calorifugeage de canalisations chaudes / ECS / chaufferie (liste A).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Présence d\'un calorifugeage sur les canalisations ECS ou chauffage ?',
          keywords: ['calorifugeage', 'calorifuge', 'canalisation', 'tuyau isolé', 'gaine'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_roof',
          field_name: 'amiante.roof_materials',
          description_short: 'Toiture (fibrociment, ardoise)',
          description_full: 'Plaques fibrociment, ardoises Eternit, gouttières, conduits cheminée.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'La toiture comporte-t-elle des plaques fibrociment ou ardoises Eternit ?',
          keywords: ['fibrociment', 'fibro-ciment', 'eternit', 'ardoise', 'toiture', 'plaque ondulée'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_window_putty',
          field_name: 'amiante.window_putty',
          description_short: 'Joints / mastics fenêtres',
          description_full: 'Mastics de fenêtre, joints chassis métalliques (liste B).',
          scope: 'per_room',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Présence de mastics ou joints suspects sur les fenêtres ?',
          keywords: ['mastic', 'joint', 'fenêtre', 'châssis'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_conduit',
          field_name: 'amiante.conduits',
          description_short: 'Conduits VMC / cheminée',
          description_full: 'Conduits VMC, conduits fumée fibrociment, gaines techniques.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quels sont les matériaux des conduits VMC et fumée ?',
          keywords: ['conduit', 'cheminée', 'vmc', 'gaine', 'fumée'],
          diagnostic: 'amiante',
        },
      ],
    },
    {
      id: 'sampling',
      label: 'Prélèvements et analyses',
      items: [
        {
          id: 'amiante_sample_decision',
          field_name: 'amiante.sample_required',
          description_short: 'Prélèvement décidé',
          description_full: 'Décision motivée de prélever / ne pas prélever, justifiée si doute.',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Faut-il prélever sur ce matériau suspect ?',
          keywords: ['prélèvement', 'prélever', 'échantillon', 'analyse'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_sample_location',
          field_name: 'amiante.sample_location',
          description_short: 'Localisation prélèvement',
          description_full: 'Localisation précise (pièce + zone + dimensions), photo avant/après.',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Localisation exacte du prélèvement (pièce + zone) ?',
          keywords: ['localisation', 'zone', 'pièce', 'emplacement', 'mètres', 'cote'],
          diagnostic: 'amiante',
        },
        {
          id: 'amiante_lab',
          field_name: 'amiante.lab_cofrac',
          description_short: 'Laboratoire COFRAC',
          description_full: 'Laboratoire COFRAC mentionné (envoi prélèvements analyse meta).',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.extended,
          trigger_question_text: 'À quel laboratoire COFRAC envoyez-vous les prélèvements ?',
          keywords: ['cofrac', 'laboratoire', 'labo', 'meta', 'analyse'],
          diagnostic: 'amiante',
        },
      ],
    },
    {
      id: 'conservation_state',
      label: 'État de conservation',
      items: [
        {
          id: 'amiante_state_grading',
          field_name: 'amiante.state_grade',
          description_short: 'Note état de conservation (1/2/3)',
          description_full: 'Cotation 1 (bon) / 2 (état intermédiaire) / 3 (dégradé) selon grilles annexe 13-9.',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle note d\'état de conservation pour ce matériau (1/2/3) ?',
          keywords: ['état de conservation', 'note 1', 'note 2', 'note 3', 'dégradé', 'bon état'],
          diagnostic: 'amiante',
        },
      ],
    },
    {
      id: 'report',
      label: 'Rapport et annexes',
      items: [
        {
          id: 'amiante_photo_per_finding',
          field_name: 'amiante.photo_per_finding',
          description_short: 'Photo de chaque MPCA détecté',
          description_full: 'Au moins 1 photo par matériau suspect ou positif identifié.',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Avez-vous bien photographié chaque MPCA repéré ?',
          keywords: ['photo', 'cliché', 'illustration'],
          diagnostic: 'amiante',
        },
      ],
    },
  ],
}
