/**
 * Checklist DPE (Diagnostic de Performance Énergétique).
 *
 * Conforme à la méthode 3CL-DPE-2021 (ADEME) — 30 items répartis sur
 * 7 sections : adresse / enveloppe / chauffage / ECS / refroidissement /
 * ventilation / éclairage-occupants.
 *
 * Keywords issus du lexique métier `diagnostic-jargon.ts` :
 * - méthode 3CL, kWhEP/m².an, étiquettes A-G, GES
 * - chaudières (gaz/fioul/granulés/PAC), ECS, plancher chauffant
 * - isolation murs/combles/sol, menuiseries, ponts thermiques
 * - VMC simple/double flux, hygroréglable, conduits
 */

import { TRIGGER_DELAYS, type DiagnosticChecklist } from './types'

export const DPE_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'dpe',
  short_label: 'DPE',
  long_label: 'Diagnostic de Performance Énergétique',
  sections: [
    {
      id: 'identification',
      label: 'Identification du bien',
      items: [
        {
          id: 'dpe_address',
          field_name: 'property.address',
          description_short: 'Adresse complète',
          description_full: 'Adresse postale précise du bien (n° voie + ville + CP).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'Pouvez-vous confirmer l\'adresse exacte du bien ?',
          keywords: ['adresse', 'rue', 'avenue', 'boulevard', 'numéro', 'code postal'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_year_built',
          field_name: 'property.year_built',
          description_short: 'Année de construction',
          description_full: 'Année de construction du bâtiment (déclaration propriétaire + acte si dispo).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'En quelle année le bien a-t-il été construit ?',
          keywords: ['année', 'construction', 'construit', 'bâti', 'date'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_surface',
          field_name: 'property.surface_habitable',
          description_short: 'Surface habitable',
          description_full: 'Surface habitable réglementaire en m² (au sens de l\'article R.156-1).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Quelle est la surface habitable totale du bien ?',
          keywords: ['surface', 'm²', 'mètres carrés', 'habitable', 'mètre carré'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_type',
          field_name: 'property.type',
          description_short: 'Type de bien',
          description_full: 'Appartement / maison individuelle / immeuble collectif.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'S\'agit-il d\'un appartement, d\'une maison ou d\'un immeuble collectif ?',
          keywords: ['appartement', 'maison', 'individuel', 'collectif', 'immeuble', 'pavillon'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_floor',
          field_name: 'property.floor_number',
          description_short: 'Étage / niveau',
          description_full: 'Étage du logement pour appartement, ou nombre de niveaux pour maison.',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'À quel étage se situe le logement ?',
          keywords: ['étage', 'rez-de-chaussée', 'niveau', 'rdc'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'envelope',
      label: 'Enveloppe du bâtiment',
      items: [
        {
          id: 'dpe_wall_type',
          field_name: 'envelope.wall_type',
          description_short: 'Matériau des murs',
          description_full: 'Matériau principal des murs extérieurs (brique / parpaing / pierre / béton / pisé).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel est le matériau principal des murs extérieurs ?',
          keywords: ['mur', 'brique', 'parpaing', 'pierre', 'béton', 'pisé', 'mâchefer', 'ossature bois'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_wall_insulation',
          field_name: 'envelope.wall_insulation',
          description_short: 'Isolation des murs',
          description_full: 'ITI / ITE / non isolé + épaisseur si visible.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les murs sont-ils isolés (ITI / ITE) ? Si oui, quelle épaisseur ?',
          keywords: ['isolation', 'isolé', 'iti', 'ite', 'laine', 'polystyrène', 'doublage', 'épaisseur'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_roof_insulation',
          field_name: 'envelope.roof_insulation',
          description_short: 'Isolation toiture/combles',
          description_full: 'Isolation combles perdus / rampants / toiture-terrasse + épaisseur.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les combles ou la toiture sont-ils isolés ? Épaisseur visible ?',
          keywords: ['combles', 'toiture', 'rampants', 'isolation toiture', 'laine de verre', 'ouate'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_floor_insulation',
          field_name: 'envelope.floor_insulation',
          description_short: 'Isolation plancher bas',
          description_full: 'Plancher sur terre-plein / vide sanitaire / sous-sol + isolation éventuelle.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Le plancher bas est-il isolé ? Sur vide sanitaire ou terre-plein ?',
          keywords: ['plancher', 'vide sanitaire', 'terre-plein', 'sous-sol', 'cave', 'isolation sol'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_windows',
          field_name: 'envelope.windows',
          description_short: 'Menuiseries (fenêtres)',
          description_full: 'Type vitrage (simple/double/triple), matériau cadre (PVC/bois/alu), %  surface.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel type de vitrage et de menuiseries (PVC / bois / alu, simple / double / triple) ?',
          keywords: ['fenêtre', 'menuiserie', 'vitrage', 'double vitrage', 'simple vitrage', 'pvc', 'baie vitrée'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_orientation',
          field_name: 'envelope.orientation',
          description_short: 'Orientation principale',
          description_full: 'Orientation des façades principales (N/E/S/O) pour calcul apports solaires.',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle est l\'orientation principale du bien ?',
          keywords: ['orientation', 'nord', 'sud', 'est', 'ouest', 'plein sud', 'exposition'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'heating',
      label: 'Chauffage',
      items: [
        {
          id: 'dpe_heating_system',
          field_name: 'heating.system_type',
          description_short: 'Système de chauffage principal',
          description_full: 'Chaudière gaz/fioul/granulés, PAC air-eau / air-air, électrique convecteur.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel est le système de chauffage principal du logement ?',
          keywords: ['chauffage', 'chaudière', 'pac', 'pompe à chaleur', 'convecteur', 'radiateur', 'poêle', 'granulés', 'fioul'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_heating_brand',
          field_name: 'heating.brand_model',
          description_short: 'Marque/modèle chaudière',
          description_full: 'Marque + modèle de la chaudière ou PAC (plaque signalétique).',
          scope: 'per_equipment',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Pouvez-vous photographier la plaque signalétique de la chaudière ?',
          keywords: ['marque', 'modèle', 'plaque', 'signalétique', 'viessmann', 'frisquet', 'saunier', 'daikin', 'atlantic'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_heating_year',
          field_name: 'heating.install_year',
          description_short: 'Année d\'installation chaudière',
          description_full: 'Année d\'installation de la chaudière / PAC (souvent gravée plaque).',
          scope: 'per_equipment',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'En quelle année la chaudière / PAC a-t-elle été installée ?',
          keywords: ['installation', 'installé', 'année', 'chaudière de', 'pose'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_heating_emitter',
          field_name: 'heating.emitter_type',
          description_short: 'Émetteurs de chaleur',
          description_full: 'Radiateurs eau / élec / plancher chauffant hydraulique ou électrique.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quels sont les émetteurs de chaleur ? Radiateurs ou plancher chauffant ?',
          keywords: ['radiateur', 'plancher chauffant', 'pch', 'émetteur', 'sèche-serviette', 'panneau rayonnant'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_thermostat',
          field_name: 'heating.thermostat',
          description_short: 'Régulation / thermostat',
          description_full: 'Programmateur, thermostat d\'ambiance, sonde extérieure, robinets thermostatiques.',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Y a-t-il un thermostat ou un programmateur de chauffage ?',
          keywords: ['thermostat', 'programmateur', 'régulation', 'sonde', 'robinet thermostatique'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'hot_water',
      label: 'Eau chaude sanitaire (ECS)',
      items: [
        {
          id: 'dpe_ecs_system',
          field_name: 'ecs.system_type',
          description_short: 'Production ECS',
          description_full: 'Ballon élec / chauffe-eau gaz / production combinée chaudière / CET / solaire.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Comment l\'eau chaude sanitaire est-elle produite ?',
          keywords: ['ecs', 'eau chaude', 'ballon', 'cumulus', 'chauffe-eau', 'thermodynamique', 'cet', 'solaire'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_ecs_volume',
          field_name: 'ecs.tank_volume',
          description_short: 'Volume du ballon',
          description_full: 'Volume du ballon ECS en litres (plaque signalétique).',
          scope: 'per_equipment',
          required: false,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Quel est le volume du ballon d\'eau chaude (en litres) ?',
          keywords: ['litres', 'volume', 'ballon de', 'capacité'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_ecs_year',
          field_name: 'ecs.install_year',
          description_short: 'Année du ballon ECS',
          description_full: 'Année d\'installation du ballon / chauffe-eau.',
          scope: 'per_equipment',
          required: false,
          severity: 'optional',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'En quelle année le ballon ECS a-t-il été installé ?',
          keywords: ['installé', 'année', 'ballon de'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'cooling',
      label: 'Refroidissement / climatisation',
      items: [
        {
          id: 'dpe_cooling_system',
          field_name: 'cooling.system_type',
          description_short: 'Climatisation présente ?',
          description_full: 'Présence et type de climatisation (split, mono, multi, PAC réversible).',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Y a-t-il une climatisation ? Si oui, quel type ?',
          keywords: ['climatisation', 'clim', 'split', 'rafraîchissement', 'réversible', 'froid'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'ventilation',
      label: 'Ventilation',
      items: [
        {
          id: 'dpe_ventilation_type',
          field_name: 'ventilation.type',
          description_short: 'Type de ventilation',
          description_full: 'Naturelle / VMC simple flux auto / hygroréglable A ou B / double flux.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel type de ventilation est en place ? VMC simple flux, hygroréglable, double flux ou naturelle ?',
          keywords: ['vmc', 'ventilation', 'simple flux', 'double flux', 'hygroréglable', 'naturelle', 'aération'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_ventilation_grilles',
          field_name: 'ventilation.grilles_state',
          description_short: 'État des grilles/bouches',
          description_full: 'Bouches d\'extraction dans pièces humides / grilles entrée air en menuiseries.',
          scope: 'per_room',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les bouches d\'extraction et grilles d\'entrée d\'air sont-elles présentes et propres ?',
          keywords: ['bouche', 'grille', 'extraction', 'entrée air', 'aération'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'lighting_occupation',
      label: 'Éclairage et occupation',
      items: [
        {
          id: 'dpe_lighting',
          field_name: 'lighting.type',
          description_short: 'Éclairage principal',
          description_full: 'LED / fluo-compact / halogène / incandescent dominant (forfaitaire 3CL).',
          scope: 'global',
          required: false,
          severity: 'optional',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.extended,
          trigger_question_text: 'L\'éclairage est-il majoritairement LED ou ancien ?',
          keywords: ['led', 'éclairage', 'ampoule', 'fluo', 'halogène'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_occupants',
          field_name: 'occupation.persons_count',
          description_short: 'Nombre d\'occupants',
          description_full: 'Nombre d\'occupants permanents (référence consommation observée).',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Combien de personnes occupent le logement à titre principal ?',
          keywords: ['occupants', 'personnes', 'foyer', 'famille', 'habitants'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_consumption_factures',
          field_name: 'occupation.energy_bills',
          description_short: 'Factures énergie 3 dernières années',
          description_full: 'Récupération factures gaz / élec / fioul sur 3 ans (méthode "consommée").',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Le propriétaire peut-il fournir les factures d\'énergie des 3 dernières années ?',
          keywords: ['facture', 'consommation', 'edf', 'engie', 'totalenergies', 'kwh', 'mwh'],
          diagnostic: 'dpe',
        },
      ],
    },
    {
      id: 'per_room',
      label: 'Observations par pièce',
      items: [
        {
          id: 'dpe_room_surface',
          field_name: 'room.surface',
          description_short: 'Surface de la pièce',
          description_full: 'Surface de la pièce visitée (au sol, mesure laser ou calcul plans).',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Quelle est la surface de cette pièce ?',
          keywords: ['surface', 'm²', 'mètres carrés', 'mesure', 'longueur', 'largeur'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_room_ceiling_height',
          field_name: 'room.ceiling_height',
          description_short: 'Hauteur sous plafond',
          description_full: 'Hauteur sous plafond en mètres (impact volume chauffé).',
          scope: 'per_room',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Quelle est la hauteur sous plafond de cette pièce ?',
          keywords: ['hauteur', 'sous plafond', 'plafond', 'm de hauteur'],
          diagnostic: 'dpe',
        },
        {
          id: 'dpe_room_photo',
          field_name: 'room.overview_photo',
          description_short: 'Photo d\'ensemble de la pièce',
          description_full: 'Au moins 1 photo d\'ensemble grand-angle de la pièce.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous pris une photo d\'ensemble de cette pièce ?',
          keywords: ['photo', 'image', 'cliché'],
          diagnostic: 'dpe',
        },
      ],
    },
  ],
}
