/**
 * Checklist Diagnostic Électrique (état des installations intérieures).
 *
 * Périmètre : installation intérieure électrique de plus de 15 ans
 * (résidentiel) selon norme XP C 16-600 — 87 points de contrôle
 * regroupés en 6 catégories (B1 à B6 + raccordement principal).
 *
 * 20 items pour la collecte terrain (synthèse des 87 points légaux).
 */

import { type DiagnosticChecklist, TRIGGER_DELAYS } from './types'

export const ELECTRICITE_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'electricite',
  short_label: 'ELEC',
  long_label: "État de l'installation intérieure d'électricité",
  sections: [
    {
      id: 'scope',
      label: 'Périmètre installation',
      items: [
        {
          id: 'elec_install_age',
          field_name: 'elec.install_age',
          description_short: 'Installation > 15 ans',
          description_full:
            "Confirmation que l'installation a plus de 15 ans (obligation diagnostic).",
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: "L'installation électrique a-t-elle bien plus de 15 ans ?",
          keywords: ['15 ans', 'installation', 'ancienneté', 'rénovée'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_norm_reference',
          field_name: 'elec.norm_reference',
          description_short: 'Norme de référence (XP C 16-600)',
          description_full: 'Confirmation usage norme XP C 16-600 (en vigueur depuis 2018).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Le diagnostic est-il bien réalisé selon XP C 16-600 ?',
          keywords: ['xp c 16-600', 'norme', 'référence'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'b1_disjoncteur_general',
      label: 'B1 — Disjoncteur de branchement',
      items: [
        {
          id: 'elec_disjoncteur_general',
          field_name: 'elec.disjoncteur_general',
          description_short: 'Disjoncteur général présent et accessible',
          description_full:
            'Présence AGCP (disjoncteur de branchement), accessible, manœuvrable, calibré.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Le disjoncteur général (AGCP) est-il présent et accessible ?',
          keywords: ['disjoncteur', 'général', 'agcp', 'branchement', 'edf', 'enedis'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_disjoncteur_caliber',
          field_name: 'elec.disjoncteur_calibre',
          description_short: 'Calibre disjoncteur (A)',
          description_full:
            'Calibre du disjoncteur (15/30, 30/45, 60 A) — adapté à la puissance souscrite.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel est le calibre du disjoncteur (15/30, 30/45, 60 A) ?',
          keywords: ['calibre', 'ampères', '30a', '45a', '60a', 'puissance'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'b2_protection_differentielle',
      label: 'B2 — Protection différentielle',
      items: [
        {
          id: 'elec_id_30ma',
          field_name: 'elec.id_30ma_count',
          description_short: 'Interrupteurs différentiels 30 mA',
          description_full:
            'Nombre et fonctionnement des ID 30 mA (type A pour plaque, type AC général).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            "Combien d'interrupteurs différentiels 30 mA, et fonctionnent-ils ?",
          keywords: ['différentiel', '30 ma', 'interrupteur', 'id', 'type a', 'type ac'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_id_test',
          field_name: 'elec.id_test_result',
          description_short: 'Test bouton ID',
          description_full:
            'Vérification fonctionnement par bouton test (déclenchement instantané).',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les ID déclenchent-ils bien sur appui bouton test ?',
          keywords: ['test', 'bouton', 'déclenchement', 'fonctionne'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'b3_terre',
      label: 'B3 — Prise de terre et liaisons',
      items: [
        {
          id: 'elec_prise_terre',
          field_name: 'elec.terre_present',
          description_short: 'Prise de terre présente',
          description_full:
            'Présence prise de terre + barrette de coupure + valeur résistance < 100 Ω.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'La prise de terre est-elle présente et mesurée ?',
          keywords: ['prise de terre', 'terre', 'barrette', 'résistance', 'ohm'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_terre_value',
          field_name: 'elec.terre_resistance',
          description_short: 'Valeur résistance de terre',
          description_full: 'Mesure résistance terre (ohms) — doit être < 100 Ω pour ID 500 mA.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle est la valeur mesurée de la résistance de terre ?',
          keywords: ['résistance', 'ohm', 'mesure terre', 'tellurohmètre'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_liaison_equipotentielle',
          field_name: 'elec.liaison_eq',
          description_short: 'Liaison équipotentielle salle de bain',
          description_full:
            'Liaison équipotentielle locale (LEL) en salle de bain, raccordée à terre.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'La liaison équipotentielle locale en salle de bain est-elle bien raccordée ?',
          keywords: ['liaison', 'équipotentielle', 'lel', 'salle de bain', 'masse'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'b4_tableau',
      label: 'B4 — Tableau et protections',
      items: [
        {
          id: 'elec_tableau_photo',
          field_name: 'elec.tableau_photo',
          description_short: 'Photo tableau électrique global',
          description_full: 'Photo du tableau ouvert (toutes protections visibles, étiquetage).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous photographié le tableau électrique ouvert ?',
          keywords: ['tableau', 'photo', 'protection', 'disjoncteur divisionnaire'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_disjoncteur_divisionnaire',
          field_name: 'elec.disjoncteurs_div',
          description_short: 'Disjoncteurs divisionnaires',
          description_full:
            'Calibres adaptés aux circuits (10A éclairage, 16A prises, 20A spéciaux, 32A cuisson).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'Les calibres des disjoncteurs divisionnaires sont-ils adaptés aux circuits ?',
          keywords: ['disjoncteur', 'divisionnaire', '10a', '16a', '20a', '32a', 'circuit'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_etiquetage',
          field_name: 'elec.tableau_etiquetage',
          description_short: 'Étiquetage des circuits',
          description_full: 'Étiquetage clair de chaque circuit (cuisine, chambre, sdb…).',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les circuits du tableau sont-ils correctement étiquetés ?',
          keywords: ['étiquette', 'étiquetage', 'libellé', 'circuit'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_fusibles_anciens',
          field_name: 'elec.fusibles_anciens',
          description_short: 'Présence fusibles à porcelaine',
          description_full: 'Fusibles à porcelaine ou rechargeables (anomalie B5).',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Y a-t-il des fusibles à porcelaine ou rechargeables ?',
          keywords: ['fusible', 'porcelaine', 'rechargeable', 'plomb fusible'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'b5_b6_appareillage',
      label: 'B5/B6 — Appareillage et locaux humides',
      items: [
        {
          id: 'elec_prises_terre',
          field_name: 'elec.prises_terre',
          description_short: 'Prises avec terre',
          description_full: 'Vérification présence terre sur toutes prises 2P+T.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Les prises sont-elles bien câblées avec la terre ?',
          keywords: ['prise', 'terre', '2p+t', 'borne terre', 'broche'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_materiel_vétuste',
          field_name: 'elec.materiel_vetuste',
          description_short: 'Matériel vétuste / inadapté',
          description_full:
            'Fils dénudés, ruban adhésif, dominos accessibles, prolongateurs en série.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'Repérez-vous du matériel vétuste, fils dénudés ou dominos accessibles ?',
          keywords: ['vétuste', 'dénudé', 'domino', 'prolongateur', 'rallonge', 'multiprise'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_sdb_volumes',
          field_name: 'elec.sdb_volumes',
          description_short: 'Respect volumes salle de bain',
          description_full:
            'Vérification respect des volumes V0/V1/V2 (indice IP, hauteur, distance).',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'Dans la salle de bain, les volumes V0/V1/V2 sont-ils bien respectés ?',
          keywords: ['volume', 'v0', 'v1', 'v2', 'salle de bain', 'ip', 'douche', 'baignoire'],
          diagnostic: 'electricite',
        },
        {
          id: 'elec_circuits_specialises',
          field_name: 'elec.circuits_specialises',
          description_short: 'Circuits spécialisés (cuisson, lavage)',
          description_full: 'Circuits dédiés plaque cuisson 32A, lave-linge / vaisselle 20A.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'Les circuits spécialisés (cuisson, lave-linge) sont-ils bien dédiés ?',
          keywords: ['circuit spécialisé', 'cuisson', 'lave-linge', 'lave-vaisselle', '32a', '20a'],
          diagnostic: 'electricite',
        },
      ],
    },
    {
      id: 'anomalies',
      label: 'Anomalies finales',
      items: [
        {
          id: 'elec_anomalies_count',
          field_name: 'elec.anomalies_total',
          description_short: 'Décompte anomalies (B1 à B6)',
          description_full: 'Décompte total et catégorisation des anomalies remontées.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: "Combien d'anomalies au total, et dans quelles catégories ?",
          keywords: ['anomalie', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'décompte'],
          diagnostic: 'electricite',
        },
      ],
    },
  ],
}
