/**
 * Checklist ERP (État des Risques et Pollutions).
 *
 * Périmètre : tout bien (vente ou location) — formulaire ERP basé
 * sur le service Géorisques (risques naturels, miniers, technologiques,
 * radon, pollution sols, sismicité).
 *
 * 9 items répartis sur 3 sections : commune & risques / radon-sismicité /
 * pollutions et sinistres antérieurs.
 */

import { type DiagnosticChecklist, TRIGGER_DELAYS } from './types'

export const ERP_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'erp',
  short_label: 'ERP',
  long_label: 'État des Risques et Pollutions',
  sections: [
    {
      id: 'commune_risks',
      label: 'Commune et risques officiels',
      items: [
        {
          id: 'erp_commune_code',
          field_name: 'erp.commune_code',
          description_short: 'Code INSEE commune',
          description_full: 'Code INSEE de la commune (clé API Géorisques).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'Code INSEE de la commune (5 chiffres) ?',
          keywords: ['insee', 'commune', 'code', 'géorisques'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_pprn',
          field_name: 'erp.pprn',
          description_short: 'PPRN (Plan Prévention Risques Naturels)',
          description_full:
            'Périmètre PPRN (inondation, mouvement terrain, sécheresse, feu, avalanche).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'La commune est-elle concernée par un PPRN ?',
          keywords: ['pprn', 'plan prévention', 'inondation', 'mouvement terrain', 'sécheresse'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_pprt',
          field_name: 'erp.pprt',
          description_short: 'PPRT (technologique)',
          description_full: 'Périmètre PPRT (Plan Prévention Risques Technologiques, SEVESO).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'La commune est-elle concernée par un PPRT (industriel) ?',
          keywords: ['pprt', 'technologique', 'seveso', 'industriel'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_pprm',
          field_name: 'erp.pprm',
          description_short: 'PPRM (minier)',
          description_full: 'Périmètre PPRM (Plan Prévention Risques Miniers).',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'La commune est-elle concernée par un PPRM (minier) ?',
          keywords: ['pprm', 'minier', 'mine', 'cavité'],
          diagnostic: 'erp',
        },
      ],
    },
    {
      id: 'natural_factors',
      label: 'Radon et sismicité',
      items: [
        {
          id: 'erp_radon',
          field_name: 'erp.radon_class',
          description_short: 'Classe radon (1/2/3)',
          description_full: 'Classe radon de la commune (3 = potentiel significatif).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle est la classe radon de la commune (1, 2 ou 3) ?',
          keywords: ['radon', 'classe 1', 'classe 2', 'classe 3', 'gaz radioactif'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_sismicite',
          field_name: 'erp.sismic_zone',
          description_short: 'Zone sismique (1-5)',
          description_full: 'Zone sismique (1 très faible → 5 forte) selon décret 2010-1255.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle est la zone sismique (1, 2, 3, 4 ou 5) ?',
          keywords: ['sismique', 'sismicité', 'zone', 'séisme'],
          diagnostic: 'erp',
        },
      ],
    },
    {
      id: 'pollution_sinistres',
      label: 'Pollutions et sinistres',
      items: [
        {
          id: 'erp_pollution_sols',
          field_name: 'erp.soil_pollution',
          description_short: 'Sites pollués (BASOL/BASIAS)',
          description_full: 'Recensement sites pollués référencés BASOL ou BASIAS.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Présence sites BASOL/BASIAS sur la parcelle ou à proximité ?',
          keywords: ['basol', 'basias', 'pollution', 'sol pollué', 'sis'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_sinistres',
          field_name: 'erp.previous_claims',
          description_short: 'Sinistres antérieurs CatNat',
          description_full:
            "Sinistres indemnisés au titre d'arrêté CatNat (à déclarer par le vendeur).",
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Sinistres CatNat antérieurs indemnisés sur le bien ?',
          keywords: ['catnat', 'sinistre', 'catastrophe naturelle', 'indemnisé'],
          diagnostic: 'erp',
        },
        {
          id: 'erp_signed',
          field_name: 'erp.signed_by_owner',
          description_short: 'Signature ERP par le vendeur',
          description_full: 'Formulaire ERP signé et daté par le vendeur/bailleur.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.extended,
          trigger_question_text: 'Le formulaire ERP est-il signé par le propriétaire ?',
          keywords: ['signature', 'signé', 'vendeur', 'bailleur', 'propriétaire'],
          diagnostic: 'erp',
        },
      ],
    },
  ],
}
