/**
 * Checklist Diagnostic Gaz (état des installations intérieures gaz).
 *
 * Périmètre : installation intérieure de gaz combustible de plus de 15 ans
 * (résidentiel) — selon norme NF P 45-500 + GAZ DGI / DGSP / A2P / A2R.
 *
 * 16 items répartis sur 5 sections : périmètre / appareils / tuyauteries /
 * ventilation / anomalies + raccordement.
 */

import { type DiagnosticChecklist, TRIGGER_DELAYS } from './types'

export const GAZ_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'gaz',
  short_label: 'GAZ',
  long_label: "État de l'installation intérieure de gaz",
  sections: [
    {
      id: 'scope',
      label: 'Périmètre installation',
      items: [
        {
          id: 'gaz_install_age',
          field_name: 'gaz.install_age',
          description_short: 'Installation > 15 ans',
          description_full:
            "Confirmation que l'installation a plus de 15 ans (obligation diagnostic).",
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: "L'installation gaz a-t-elle bien plus de 15 ans ?",
          keywords: ['15 ans', 'installation', 'ancienneté', 'date installation'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_type_gaz',
          field_name: 'gaz.gas_type',
          description_short: 'Type de gaz (naturel / propane / butane)',
          description_full: 'Gaz naturel réseau, propane citerne, butane bouteilles.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: "S'agit-il de gaz naturel, propane ou butane ?",
          keywords: ['gaz naturel', 'propane', 'butane', 'citerne', 'bouteille', 'réseau'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_compteur',
          field_name: 'gaz.compteur_location',
          description_short: 'Localisation compteur',
          description_full: 'Compteur visible, accessible, n° PCE pour gaz naturel.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Où se situe le compteur gaz ? Avez-vous photographié le n° PCE ?',
          keywords: ['compteur', 'pce', 'gaz', 'point comptage'],
          diagnostic: 'gaz',
        },
      ],
    },
    {
      id: 'appliances',
      label: 'Appareils raccordés',
      items: [
        {
          id: 'gaz_appliances_list',
          field_name: 'gaz.appliances_list',
          description_short: 'Inventaire des appareils gaz',
          description_full:
            'Liste exhaustive (chaudière, plaque cuisson, four, chauffe-bain, radiant).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            'Quels appareils gaz sont raccordés (chaudière, plaque, chauffe-bain) ?',
          keywords: [
            'chaudière',
            'plaque',
            'cuisinière',
            'chauffe-bain',
            'four',
            'radiant',
            'appareil gaz',
          ],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_appliance_type',
          field_name: 'gaz.appliance_type',
          description_short: 'Type appareil (A / B / C)',
          description_full:
            'Type A (non raccordé), B (raccordé avec coupe-tirage), C (étanche ventouse).',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: "L'appareil est-il de type A, B ou C (ventouse) ?",
          keywords: ['type a', 'type b', 'type c', 'ventouse', 'étanche', 'raccordé'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_appliance_brand',
          field_name: 'gaz.appliance_plate',
          description_short: 'Plaque signalétique chaudière',
          description_full: 'Photo plaque signalétique (marque, modèle, débit, ESS, NF).',
          scope: 'per_equipment',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Avez-vous photographié la plaque signalétique de la chaudière ?',
          keywords: ['plaque', 'signalétique', 'marque', 'modèle', 'débit'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_appliance_entretien',
          field_name: 'gaz.appliance_maintenance',
          description_short: 'Attestation entretien annuel',
          description_full:
            'Justificatif entretien annuel chaudière (obligatoire art. R224-41-4 CE).',
          scope: 'per_equipment',
          required: true,
          severity: 'important',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text:
            "Le propriétaire a-t-il l'attestation d'entretien annuel de la chaudière ?",
          keywords: ['entretien', 'annuel', 'attestation', 'maintenance'],
          diagnostic: 'gaz',
        },
      ],
    },
    {
      id: 'piping',
      label: 'Tuyauteries et raccordements',
      items: [
        {
          id: 'gaz_pipe_material',
          field_name: 'gaz.pipe_material',
          description_short: 'Matériau tuyauteries',
          description_full: 'Cuivre, acier, PE-multicouche, tube souple (caoutchouc interdit).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quel matériau pour les tuyauteries gaz ? Souple ou rigide ?',
          keywords: ['tuyauterie', 'cuivre', 'acier', 'souple', 'rigide', 'flexible', 'tube'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_pipe_flexible_date',
          field_name: 'gaz.flexible_validity',
          description_short: 'Date péremption flexibles',
          description_full:
            'Date de validité des flexibles à embouts mécaniques (anciennement caoutchouc).',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Les flexibles sont-ils en cours de validité ?',
          keywords: ['flexible', 'péremption', 'validité', 'embout', 'tuyau souple'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_pipe_route',
          field_name: 'gaz.pipe_route',
          description_short: 'Cheminement tuyauteries',
          description_full: 'Cheminement encastré/apparent, traversées de murs, gaines techniques.',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            "Le cheminement des tuyaux est-il conforme (pas d'encastrement non gainé) ?",
          keywords: ['cheminement', 'encastré', 'apparent', 'gaine', 'traversée'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_robinet_coupure',
          field_name: 'gaz.shutoff_valve',
          description_short: 'Robinet de coupure générale',
          description_full: 'Robinet de coupure générale visible, accessible, manœuvrable.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Le robinet de coupure générale est-il bien accessible ?',
          keywords: ['robinet', 'coupure', 'générale', 'vanne', 'arrêt'],
          diagnostic: 'gaz',
        },
      ],
    },
    {
      id: 'combustion_ventilation',
      label: 'Combustion et ventilation',
      items: [
        {
          id: 'gaz_co_test',
          field_name: 'gaz.co_test',
          description_short: 'Mesure CO ambiant',
          description_full: 'Mesure CO ambiant pièce où fonctionne appareil type A ou B.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Avez-vous mesuré le monoxyde de carbone (CO) ?',
          keywords: ['co', 'monoxyde', 'carbone', 'mesure ambiant'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_evacuation',
          field_name: 'gaz.flue_evacuation',
          description_short: 'Évacuation produits combustion',
          description_full: 'Conduit fumée conforme, ventouse, dévoiement, tirage.',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: "L'évacuation des produits de combustion est-elle conforme ?",
          keywords: ['conduit', 'fumée', 'évacuation', 'ventouse', 'tirage'],
          diagnostic: 'gaz',
        },
        {
          id: 'gaz_ventilation_amenees',
          field_name: 'gaz.air_intake',
          description_short: "Amenées d'air comburant",
          description_full: "Grilles, entrées d'air haute et basse, vmc-gaz si applicable.",
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text:
            "Les amenées d'air comburant sont-elles correctement dimensionnées ?",
          keywords: ['amenée', 'air', 'grille', 'comburant', 'vmc-gaz', 'entrée'],
          diagnostic: 'gaz',
        },
      ],
    },
    {
      id: 'anomalies',
      label: 'Anomalies et conclusion',
      items: [
        {
          id: 'gaz_anomalies_class',
          field_name: 'gaz.anomalies_classification',
          description_short: 'Classement anomalies (A1/A2/DGI/DGSP)',
          description_full:
            'A1 (réparer), A2 (réparer rapidement), DGI (danger grave immédiat) → coupure.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Avez-vous classé les anomalies (A1, A2, DGI ou DGSP) ?',
          keywords: ['a1', 'a2', 'dgi', 'dgsp', 'danger grave', 'anomalie'],
          diagnostic: 'gaz',
        },
      ],
    },
  ],
}
