/**
 * Checklist Plomb — CREP (Constat de Risque d'Exposition au Plomb).
 *
 * Périmètre métier : bien construit avant le 1er janvier 1949 — mesure
 * fluorescence X (XRF) sur tous les revêtements accessibles, dégradés
 * ou non, des parties privatives.
 *
 * 14 items répartis sur 4 sections : périmètre / appareil / unités diag /
 * classement de chaque unité.
 */

import { TRIGGER_DELAYS, type DiagnosticChecklist } from './types'

export const PLOMB_CHECKLIST: DiagnosticChecklist = {
  diagnostic: 'plomb',
  short_label: 'PLOMB',
  long_label: 'CREP — Constat de Risque d\'Exposition au Plomb',
  sections: [
    {
      id: 'scope',
      label: 'Périmètre du CREP',
      items: [
        {
          id: 'plomb_pre_1949',
          field_name: 'plomb.pre_1949_check',
          description_short: 'PC déposé avant 1949',
          description_full: 'Confirmation que le permis de construire est antérieur au 1er janvier 1949 (sinon CREP non requis).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'Le permis de construire est-il bien antérieur à 1949 ?',
          keywords: ['1949', 'avant 1949', 'permis', 'antérieur'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_mission_type',
          field_name: 'plomb.mission_type',
          description_short: 'Type CREP (vente/location/travaux)',
          description_full: 'CREP vente, location, ou avant travaux (impact sur durée validité).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.fast,
          trigger_question_text: 'CREP pour vente, location ou avant travaux ?',
          keywords: ['vente', 'location', 'avant travaux', 'crep'],
          diagnostic: 'plomb',
        },
      ],
    },
    {
      id: 'equipment',
      label: 'Appareil de mesure',
      items: [
        {
          id: 'plomb_xrf_brand',
          field_name: 'plomb.xrf_device',
          description_short: 'Marque/modèle appareil XRF',
          description_full: 'Marque + modèle + n° de série de l\'appareil fluorescence X (Niton, Thermo, Innov-X, Olympus).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Quelle marque/modèle d\'appareil XRF utilisez-vous ?',
          keywords: ['xrf', 'fluorescence', 'niton', 'innov-x', 'olympus', 'thermo', 'appareil plomb'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_xrf_calibration',
          field_name: 'plomb.xrf_calibration',
          description_short: 'Étalonnage / vérification appareil',
          description_full: 'Date dernière calibration / certificat de vérification (≤ 1 an).',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'L\'appareil XRF est-il bien étalonné (vérification < 1 an) ?',
          keywords: ['étalonnage', 'calibration', 'vérification', 'certificat', 'cofrac'],
          diagnostic: 'plomb',
        },
      ],
    },
    {
      id: 'measurement_units',
      label: 'Unités de diagnostic',
      items: [
        {
          id: 'plomb_unit_count',
          field_name: 'plomb.units_count',
          description_short: 'Nombre total d\'unités diag',
          description_full: 'Nombre total d\'unités de diagnostic (UD) à mesurer par pièce.',
          scope: 'global',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Combien d\'unités de diagnostic au total ?',
          keywords: ['unité', 'unités', 'ud', 'unité de diagnostic'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_walls',
          field_name: 'plomb.walls_measured',
          description_short: 'Mesure des murs',
          description_full: 'Mesure XRF sur chaque mur de chaque pièce visitée.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous mesuré chaque mur de cette pièce ?',
          keywords: ['mur', 'mesure', 'tir', 'xrf', 'face'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_ceiling',
          field_name: 'plomb.ceiling_measured',
          description_short: 'Mesure du plafond',
          description_full: 'Mesure XRF sur le plafond de chaque pièce.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous mesuré le plafond de cette pièce ?',
          keywords: ['plafond', 'tir plafond', 'mesure plafond'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_doors',
          field_name: 'plomb.doors_measured',
          description_short: 'Mesure portes et huisseries',
          description_full: 'Mesure XRF sur portes, huisseries, dormants, plinthes.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous mesuré portes, huisseries et plinthes de cette pièce ?',
          keywords: ['porte', 'huisserie', 'dormant', 'plinthe', 'chambranle'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_windows',
          field_name: 'plomb.windows_measured',
          description_short: 'Mesure fenêtres et radiateurs',
          description_full: 'Mesure XRF sur fenêtres, volets, radiateurs.',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.short,
          trigger_question_text: 'Avez-vous mesuré fenêtres, volets et radiateurs ?',
          keywords: ['fenêtre', 'volet', 'radiateur', 'mesure'],
          diagnostic: 'plomb',
        },
      ],
    },
    {
      id: 'classification',
      label: 'Classement des unités',
      items: [
        {
          id: 'plomb_class_per_unit',
          field_name: 'plomb.class_per_unit',
          description_short: 'Classe 0/1/2/3 par UD',
          description_full: 'Classement chaque UD : 0 (rien) / 1 (non dégradé) / 2 (peu dégradé) / 3 (dégradé risque).',
          scope: 'per_room',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Classe 0/1/2/3 à attribuer pour chaque UD positive ?',
          keywords: ['classe', 'classe 1', 'classe 2', 'classe 3', 'dégradé', 'non dégradé'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_degradation_photo',
          field_name: 'plomb.degradation_photos',
          description_short: 'Photo des UD classe 3',
          description_full: 'Photo obligatoire pour chaque UD classée 3 (revêtement dégradé).',
          scope: 'per_equipment',
          required: true,
          severity: 'critical',
          requires_photo: true,
          trigger_question_after_ms: TRIGGER_DELAYS.medium,
          trigger_question_text: 'Avez-vous photographié les UD classe 3 (dégradées) ?',
          keywords: ['photo', 'dégradé', 'écaillé', 'écaillement'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_silex',
          field_name: 'plomb.factors_silex',
          description_short: 'Facteurs dégradation bâti',
          description_full: 'Recherche facteurs dégradation bâti (humidité, infiltration).',
          scope: 'global',
          required: false,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.long,
          trigger_question_text: 'Y a-t-il des facteurs de dégradation du bâti (humidité) ?',
          keywords: ['humidité', 'infiltration', 'dégradation bâti', 'moisissure'],
          diagnostic: 'plomb',
        },
        {
          id: 'plomb_recommendations',
          field_name: 'plomb.recommendations',
          description_short: 'Recommandations propriétaire',
          description_full: 'Notice information remise au propriétaire (obligation si UD classes 1/2/3 ou EHS).',
          scope: 'global',
          required: true,
          severity: 'important',
          requires_photo: false,
          trigger_question_after_ms: TRIGGER_DELAYS.extended,
          trigger_question_text: 'La notice information propriétaire a-t-elle été remise ?',
          keywords: ['notice', 'information', 'recommandation', 'travaux'],
          diagnostic: 'plomb',
        },
      ],
    },
  ],
}
